INSERT INTO MENU_CATEGORY (category_name, description) VALUES
('Starters', 'Small plates to begin your meal'),
('Main Courses', 'Hearty and filling main dishes'),
('Desserts', 'Sweet treats and cakes'),
('Beverages', 'Refreshing cold and hot drinks'),
('Vegan', 'Plant-based delicious dishes'),
('Seafood', 'Fresh catch from the ocean'),
('Pasta', 'Authentic Italian pasta varieties'),
('Pizza', 'Wood-fired artisanal pizzas'),
('Burgers', 'Gourmet burgers with premium beef'),
('Steaks', 'Prime cuts of grilled meat'),
('Salads', 'Fresh and healthy leafy greens'),
('Soups', 'Warm and comforting liquid starters'),
('Breakfast', 'Morning favorites to start the day'),
('Brunch', 'Late morning weekend specials'),
('Sandwiches', 'Freshly made wraps and subs'),
('Sides', 'Extra portions to accompany your meal'),
('Sushi', 'Traditional Japanese rolls and sashimi'),
('Tacos', 'Authentic Mexican street style tacos'),
('Tapas', 'Spanish style sharing plates'),
('Kids Menu', 'Smaller portions for our younger guests'),
('Seasonal', 'Chef specials using seasonal produce'),
('Signature', 'Our most famous house creations'),
('Cocktails', 'Handcrafted alcoholic beverages'),
('Wines', 'Selected red, white, and rosé wines'),
('Beers', 'Craft and international draught beers'),
('Coffees', 'Barista made coffee and espresso'),
('Teas', 'Premium leaf tea selection'),
('Pastries', 'Freshly baked daily in-house'),
('Grilled', 'Charcoal grilled specialties'),
('Appetizers', 'Light bites for the table');

INSERT INTO INGREDIENT (ingredient_name, unit) VALUES
('All-purpose Flour', 'kg'),
('Granulated Sugar', 'kg'),
('Sea Salt', 'kg'),
('Black Pepper', 'g'),
('Extra Virgin Olive Oil', 'liters'),
('Unsalted Butter', 'kg'),
('Whole Milk', 'liters'),
('Large Eggs', 'pcs'),
('Fresh Garlic', 'g'),
('Yellow Onion', 'kg'),
('Roma Tomato', 'kg'),
('Russet Potato', 'kg'),
('Chicken Breast', 'kg'),
('Ground Beef 80/20', 'kg'),
('Atlantic Salmon Fillet', 'kg'),
('Tiger Shrimp', 'kg'),
('Basmati Rice', 'kg'),
('Spaghetti Pasta', 'kg'),
('Fresh Basil', 'g'),
('Dried Oregano', 'g'),
('Fresh Thyme', 'g'),
('Fresh Lemons', 'pcs'),
('Mozzarella Cheese', 'kg'),
('Heavy Cream', 'liters'),
('Dark Chocolate 70%', 'kg'),
('Active Dry Yeast', 'g'),
('Fresh Parsley', 'g'),
('Organic Honey', 'kg'),
('Ground Cinnamon', 'g'),
('Vanilla Extract', 'ml');

INSERT INTO MENU_ITEM (item_name, price, description, is_available, category_id) VALUES
('Classic Bruschetta', 8.50, 'Toasted bread with garlic and tomatoes', TRUE, 1),
('Grilled Ribeye', 34.99, '12oz prime beef served with butter', TRUE, 2),
('Chocolate Lava Cake', 7.50, 'Warm chocolate cake with melting center', TRUE, 3),
('Fresh Lemonade', 4.00, 'Hand-squeezed lemons and cane sugar', TRUE, 4),
('Vegan Buddha Bowl', 14.00, 'Quinoa, chickpeas and roasted veggies', TRUE, 5),
('Grilled Sea Bass', 28.00, 'Mediteranean style with lemon and herbs', TRUE, 6),
('Fettuccine Alfredo', 16.50, 'Creamy parmesan sauce with handmade pasta', TRUE, 7),
('Margherita Pizza', 13.00, 'Fresh mozzarella, basil and tomato sauce', TRUE, 8),
('Bacon BBQ Burger', 15.50, 'Beef patty, smoked bacon and bbq sauce', TRUE, 9),
('T-Bone Steak', 42.00, 'Dry-aged 16oz steak grilled to order', TRUE, 10),
('Caesar Salad', 11.00, 'Romaine lettuce, croutons and dressing', TRUE, 11),
('Tomato Basil Soup', 6.50, 'Creamy tomato soup with fresh basil', TRUE, 12),
('Eggs Benedict', 13.50, 'Poached eggs on muffin with hollandaise', TRUE, 13),
('Smoked Salmon Toast', 14.50, 'Avocado and salmon on sourdough', TRUE, 14),
('Chicken Club Sandwich', 12.50, 'Triple decker with chicken and bacon', TRUE, 15),
('Truffle Fries', 6.00, 'Crispy fries with truffle oil and salt', TRUE, 16),
('California Roll', 18.00, 'Crab, avocado and cucumber sushi', TRUE, 17),
('Beef Barbacoa Tacos', 12.00, 'Slow cooked beef in corn tortillas', TRUE, 18),
('Garlic Gambas', 10.50, 'Shrimp cooked in sizzling garlic oil', TRUE, 19),
('Mini Cheese Burger', 9.00, 'Small burger served with fries', TRUE, 20),
('Summer Berry Tart', 8.00, 'Seasonal berries on a pastry shell', TRUE, 21),
('Signature Truffle Pasta', 22.00, 'Our house specialty with black truffle', TRUE, 22),
('Old Fashioned', 12.00, 'Bourbon, bitters and orange peel', TRUE, 23),
('Chardonnay Glass', 9.50, 'Crisp white wine from California', TRUE, 24),
('Local Craft IPA', 7.00, 'Brewed locally with citrus hops', TRUE, 25),
('Double Espresso', 3.50, 'Strong and dark roasted coffee', TRUE, 26),
('Earl Grey Tea', 3.00, 'Traditional black tea with bergamot', TRUE, 27),
('Butter Croissant', 4.50, 'Flaky, buttery French style pastry', TRUE, 28),
('Grilled Lamb Chops', 31.00, 'Served with mint sauce and potatoes', TRUE, 29),
('Crispy Calamari', 11.50, 'Fried squid rings with lemon aioli', TRUE, 30);

INSERT INTO RECIPE (instructions, menu_item_id) VALUES
('Slice the baguette, toast until golden, rub with raw garlic and top with tomatoes.', 1),
('Season the ribeye heavily with salt and pepper. Sear in a hot pan 4 mins per side.', 2),
('Mix cocoa, sugar, and eggs. Bake for exactly 12 minutes to keep center liquid.', 3),
('Mix 1 cup of lemon juice with 1/2 cup of sugar and 1 liter of cold water.', 4),
('Roast seasonal vegetables at 200C. Serve over boiled quinoa with tahini sauce.', 5),
('Score the skin of the sea bass, grill skin-side down first until crispy.', 6),
('Melt butter in a pan, add heavy cream and whisk in parmesan until thickened.', 7),
('Roll out dough, spread tomato sauce, add mozzarella and bake at 400C.', 8),
('Grill beef patty to medium, melt cheese on top, add crispy bacon and BBQ sauce.', 9),
('Brush steak with oil, grill for 5 minutes per side. Let rest for 10 minutes.', 10),
('Toss romaine with Caesar dressing, top with parmesan and baked croutons.', 11),
('Simmer crushed tomatoes with onions and garlic for 30 minutes. Blend smooth.', 12),
('Poach eggs in simmering water for 3 mins. Serve over ham and toasted muffin.', 13),
('Mash avocado on toast, top with smoked salmon slices and red onions.', 14),
('Toast bread, layer chicken, lettuce, tomato, and mayo in three slices.', 15),
('Fry potatoes at 180C until gold. Toss with truffle oil and sea salt.', 16),
('Spread rice on nori, add crab and avocado, roll tightly and slice into 8.', 17),
('Slow cook beef for 6 hours until shreddable. Serve in warm corn tortillas.', 18),
('Sauté shrimp in olive oil with 5 cloves of garlic and chili flakes.', 19),
('Cook small beef patty, add cheddar and serve in a brioche slider bun.', 20),
('Fill pastry shell with vanilla custard and top with fresh seasonal berries.', 21),
('Boil fresh pasta, toss with truffle cream and top with shaved truffle.', 22),
('Muddle sugar and bitters, add bourbon and stir with a large ice cube.', 23),
('Pour 150ml of chilled Chardonnay into a standard white wine glass.', 24),
('Pour draft beer slowly at a 45 degree angle to ensure 1 inch of foam.', 25),
('Grind 18g of beans, pull a 30 second shot through the espresso machine.', 26),
('Steep one tea bag in 95C water for exactly 3 minutes before serving.', 27),
('Laminate dough with butter layers, fold 3 times, shape and bake at 180C.', 28),
('Marinate lamb with rosemary, grill until medium rare. Serve with mint.', 29),
('Lightly coat squid in flour and spices, deep fry for 2 minutes total.', 30);

INSERT INTO RECIPE_INGREDIENT (quantity, recipe_id, ingredient_id) VALUES
(0.200, 1, 11), (0.400, 2, 14), (0.150, 3, 2), (0.300, 4, 22), (0.100, 5, 17),
(0.250, 6, 15), (0.200, 7, 24), (0.150, 8, 23), (0.180, 9, 14), (0.500, 10, 14),
(0.050, 11, 23), (0.400, 12, 11), (2.000, 13, 8), (0.100, 14, 15), (0.200, 15, 13),
(0.300, 16, 12), (0.100, 17, 17), (0.200, 18, 14), (0.150, 19, 16), (0.100, 20, 14),
(0.100, 21, 2), (0.200, 22, 18), (0.010, 23, 2), (0.150, 24, 7), (0.500, 25, 7),
(0.018, 26, 1), (0.005, 27, 2), (0.150, 28, 6), (0.300, 29, 14), (0.200, 30, 16);

INSERT INTO MENU_CHANGE_LOG (change_description, menu_item_id) VALUES
('Price increased due to market cost of bread', 1),
('Description updated for Ribeye steak', 2),
('Availability set to False (out of stock)', 3),
('Added new summer flavor notes', 4),
('Updated recipe to include more chickpeas', 5),
('Changed seafood supplier for better quality', 6),
('Increased portion size for pasta dishes', 7),
('Special promotion price reduction', 8),
('Changed bacon type to Maple Smoked', 9),
('Updated cooking time instructions', 10),
('Added croutons to ingredient list', 11),
('Seasonal soup rotation update', 12),
('Updated hollandaise sauce recipe', 13),
('New photo added to digital menu', 14),
('Chicken breast weight increased', 15),
('New oil type for truffle fries', 16),
('Price adjusted for inflation', 17),
('Taco platter serving size change', 18),
('Changed chili flakes used in gambas', 19),
('Modified kids menu calorie count', 20),
('Seasonal berry selection updated', 21),
('Signature dish re-launched for anniversary', 22),
('New cocktail garnish added', 23),
('Wine year updated to 2022 vintage', 24),
('New local brewery partnership', 25),
('Updated espresso machine settings', 26),
('Changed tea brand to Organic Leaf', 27),
('Morning pastry pricing update', 28),
('Added rosemary to lamb marinade', 29),
('New supplier for calamari rings', 30);
commit;