DROP TABLE IF EXISTS RECIPE_INGREDIENT;
DROP TABLE IF EXISTS MENU_CHANGE_LOG;
DROP TABLE IF EXISTS RECIPE;
DROP TABLE IF EXISTS MENU_ITEM;
DROP TABLE IF EXISTS INGREDIENT;
DROP TABLE IF EXISTS MENU_CATEGORY;