insert into MENU_CATEGORY (category_id, category_name, description) values (1, 'Educational Toys 1', 'Inverse composite orchestration');
insert into MENU_CATEGORY (category_id, category_name, description) values (2, 'Chips and Crisps 2', 'Focused even-keeled ability');
insert into MENU_CATEGORY (category_id, category_name, description) values (3, 'Casual Dresses 3', 'Streamlined exuding conglomeration');
insert into MENU_CATEGORY (category_id, category_name, description) values (4, 'Flavored Quinoa 4', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (5, 'Dog Accessories 5', 'Adaptive well-modulated budgetary management');
insert into MENU_CATEGORY (category_id, category_name, description) values (6, 'Oils 6', 'Versatile responsive concept');
insert into MENU_CATEGORY (category_id, category_name, description) values (7, 'Baking Ingredients 7', 'Re-contextualized user-facing knowledge user');
insert into MENU_CATEGORY (category_id, category_name, description) values (8, 'Vegetarian Meal Kits 8', 'Expanded logistical focus group');
insert into MENU_CATEGORY (category_id, category_name, description) values (9, 'Camping Equipment 9', 'Object-based 5th generation adapter');
insert into MENU_CATEGORY (category_id, category_name, description) values (10, 'Frozen Snacks 10', 'Switchable multimedia framework');
insert into MENU_CATEGORY (category_id, category_name, description) values (11, 'Protein Snacks 11', 'Fully-configurable executive initiative');
insert into MENU_CATEGORY (category_id, category_name, description) values (12, 'Fruit Spreads 12', 'Right-sized attitude-oriented monitoring');
insert into MENU_CATEGORY (category_id, category_name, description) values (13, 'Lip Care 13', 'Enterprise-wide zero defect time-frame');
insert into MENU_CATEGORY (category_id, category_name, description) values (14, 'Red Meat 14', 'Reduced directional artificial intelligence');
insert into MENU_CATEGORY (category_id, category_name, description) values (15, 'Home Organization 15', 'Operative discrete firmware');
insert into MENU_CATEGORY (category_id, category_name, description) values (16, 'Lighting Equipment 16', 'Optimized tertiary architecture');
insert into MENU_CATEGORY (category_id, category_name, description) values (17, 'Wearable Technology 17', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (18, 'Small Appliances 18', 'Decentralized modular focus group');
insert into MENU_CATEGORY (category_id, category_name, description) values (19, 'Nut-Based Snacks 19', 'Robust multimedia productivity');
insert into MENU_CATEGORY (category_id, category_name, description) values (20, 'Savory Snacks 20', 'Up-sized local hardware');
insert into MENU_CATEGORY (category_id, category_name, description) values (21, 'Kitchen Accessories 21', 'Front-line 24 hour emulation');
insert into MENU_CATEGORY (category_id, category_name, description) values (22, 'Tortilla Chips 22', 'Adaptive exuding extranet');
insert into MENU_CATEGORY (category_id, category_name, description) values (23, 'Small Appliances 23', 'Operative bottom-line capability');
insert into MENU_CATEGORY (category_id, category_name, description) values (24, 'Seeds & Nuts 24', 'Optimized 6th generation groupware');
insert into MENU_CATEGORY (category_id, category_name, description) values (25, 'Health Drinks 25', 'Focused web-enabled data-warehouse');
insert into MENU_CATEGORY (category_id, category_name, description) values (26, 'T-Shirts 26', 'Stand-alone bifurcated secured line');
insert into MENU_CATEGORY (category_id, category_name, description) values (27, 'Natural Beverages 27', 'Switchable foreground website');
insert into MENU_CATEGORY (category_id, category_name, description) values (28, 'Savory Breakfast Options 28', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (29, 'Prepared Seafood 29', 'Persistent heuristic leverage');
insert into MENU_CATEGORY (category_id, category_name, description) values (30, 'Chocolate Bars 30', 'Assimilated client-driven matrix');
insert into MENU_CATEGORY (category_id, category_name, description) values (31, 'Frozen Chicken Meals 31', 'Switchable systemic archive');
insert into MENU_CATEGORY (category_id, category_name, description) values (32, 'Grains 32', 'Up-sized content-based projection');
insert into MENU_CATEGORY (category_id, category_name, description) values (33, 'Healthy Meals 33', 'Centralized demand-driven array');
insert into MENU_CATEGORY (category_id, category_name, description) values (34, 'Healthy Snacks 34', 'Realigned client-driven artificial intelligence');
insert into MENU_CATEGORY (category_id, category_name, description) values (35, 'Cycling Accessories 35', 'Customer-focused fault-tolerant groupware');
insert into MENU_CATEGORY (category_id, category_name, description) values (36, 'Hot Sauces 36', 'Triple-buffered logistical conglomeration');
insert into MENU_CATEGORY (category_id, category_name, description) values (37, 'Tortilla Chips 37', 'Self-enabling scalable open system');
insert into MENU_CATEGORY (category_id, category_name, description) values (38, 'Strength Training Equipment 38', 'Versatile real-time groupware');
insert into MENU_CATEGORY (category_id, category_name, description) values (39, 'Frozen Snacks 39', 'Devolved encompassing standardization');
insert into MENU_CATEGORY (category_id, category_name, description) values (40, 'Nuts and Trail Mix 40', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (41, 'Home Entertainment Equipment 41', 'Realigned executive hierarchy');
insert into MENU_CATEGORY (category_id, category_name, description) values (42, 'Planters 42', 'Diverse disintermediate access');
insert into MENU_CATEGORY (category_id, category_name, description) values (43, 'Baking Ingredients 43', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (44, 'Decorative Wall Art & Accessories 44', 'Future-proofed multi-state moderator');
insert into MENU_CATEGORY (category_id, category_name, description) values (45, 'Smartwatches 45', 'Proactive uniform intranet');
insert into MENU_CATEGORY (category_id, category_name, description) values (46, 'Home Automation 46', 'Sharable disintermediate flexibility');
insert into MENU_CATEGORY (category_id, category_name, description) values (47, 'Drones & Accessories 47', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (48, 'Dips and Spreads 48', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (49, 'Pretend Play Toys 49', 'Business-focused asynchronous ability');
insert into MENU_CATEGORY (category_id, category_name, description) values (50, 'Savory Snacks 50', 'Automated tertiary parallelism');
insert into MENU_CATEGORY (category_id, category_name, description) values (51, 'Salsas and Dips 51', 'Fully-configurable global matrix');
insert into MENU_CATEGORY (category_id, category_name, description) values (52, 'Camping Equipment 52', 'Implemented mobile secured line');
insert into MENU_CATEGORY (category_id, category_name, description) values (53, 'Pies & Quiches 53', 'Monitored directional database');
insert into MENU_CATEGORY (category_id, category_name, description) values (54, 'Desserts 54', 'Sharable coherent superstructure');
insert into MENU_CATEGORY (category_id, category_name, description) values (55, 'Frozen Baked Goods 55', 'Triple-buffered well-modulated capability');
insert into MENU_CATEGORY (category_id, category_name, description) values (56, 'Organizational Tools 56', 'Total zero administration middleware');
insert into MENU_CATEGORY (category_id, category_name, description) values (57, 'Nutrition & Fitness 57', 'Multi-lateral web-enabled artificial intelligence');
insert into MENU_CATEGORY (category_id, category_name, description) values (58, 'Yoga Equipment 58', 'Persevering methodical benchmark');
insert into MENU_CATEGORY (category_id, category_name, description) values (59, 'Drinkware 59', 'Distributed zero tolerance circuit');
insert into MENU_CATEGORY (category_id, category_name, description) values (60, 'Cookware 60', 'Inverse 3rd generation analyzer');
insert into MENU_CATEGORY (category_id, category_name, description) values (61, 'Granola 61', 'Managed impactful paradigm');
insert into MENU_CATEGORY (category_id, category_name, description) values (62, 'Shirts 62', 'Multi-lateral logistical software');
insert into MENU_CATEGORY (category_id, category_name, description) values (63, 'Coffee 63', 'Upgradable system-worthy archive');
insert into MENU_CATEGORY (category_id, category_name, description) values (64, 'Cheese 64', 'Pre-emptive neutral archive');
insert into MENU_CATEGORY (category_id, category_name, description) values (65, 'Small Appliances 65', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (66, 'Specialty Soups 66', 'User-centric national monitoring');
insert into MENU_CATEGORY (category_id, category_name, description) values (67, 'Japanese Cooking Kits 67', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (68, 'Dips & Spreads 68', 'Object-based 5th generation database');
insert into MENU_CATEGORY (category_id, category_name, description) values (69, 'Camping Equipment 69', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (70, 'Marinades and Sauces 70', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (71, 'Frozen Pizza 71', 'Polarised homogeneous hierarchy');
insert into MENU_CATEGORY (category_id, category_name, description) values (72, 'Herbal Tea 72', 'Streamlined bifurcated benchmark');
insert into MENU_CATEGORY (category_id, category_name, description) values (73, 'Beverage Appliances 73', 'Pre-emptive encompassing hierarchy');
insert into MENU_CATEGORY (category_id, category_name, description) values (74, 'Cooling Appliances 74', 'Exclusive exuding ability');
insert into MENU_CATEGORY (category_id, category_name, description) values (75, 'Vegetables 75', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (76, 'Ethnic Sauces 76', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (77, 'Instant Meals 77', 'Reverse-engineered systematic access');
insert into MENU_CATEGORY (category_id, category_name, description) values (78, 'Beverages 78', 'Cross-platform attitude-oriented archive');
insert into MENU_CATEGORY (category_id, category_name, description) values (79, 'Graphic Tees 79', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (80, 'Phone Accessories 80', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (81, 'Small Appliances 81', 'Sharable context-sensitive implementation');
insert into MENU_CATEGORY (category_id, category_name, description) values (82, 'Sculpting Supplies 82', 'Organized multi-state framework');
insert into MENU_CATEGORY (category_id, category_name, description) values (83, 'Casseroles 83', 'Integrated 5th generation neural-net');
insert into MENU_CATEGORY (category_id, category_name, description) values (84, 'Children''s Educational Books 84', 'Advanced encompassing knowledge user');
insert into MENU_CATEGORY (category_id, category_name, description) values (85, 'Grilling Accessories 85', 'Persistent tertiary function');
insert into MENU_CATEGORY (category_id, category_name, description) values (86, 'Oral Care & Hygiene 86', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (87, 'Decorative Wall Art & Accessories 87', 'Intuitive intermediate solution');
insert into MENU_CATEGORY (category_id, category_name, description) values (88, 'Solar Power Accessories 88', 'Phased asymmetric process improvement');
insert into MENU_CATEGORY (category_id, category_name, description) values (89, 'Headphones & Earbuds 89', 'Implemented bi-directional time-frame');
insert into MENU_CATEGORY (category_id, category_name, description) values (90, 'Marinades and Sauces 90', 'Enterprise-wide non-volatile utilisation');
insert into MENU_CATEGORY (category_id, category_name, description) values (91, 'Food Storage Solutions 91', 'Right-sized client-driven architecture');
insert into MENU_CATEGORY (category_id, category_name, description) values (92, 'Baking Ingredients 92', 'Ameliorated responsive open architecture');
insert into MENU_CATEGORY (category_id, category_name, description) values (93, 'Jerky 93', 'Digitized asynchronous open architecture');
insert into MENU_CATEGORY (category_id, category_name, description) values (94, 'Syrups 94', 'Diverse background product');
insert into MENU_CATEGORY (category_id, category_name, description) values (95, 'Frozen Fruits 95', 'Secured impactful encoding');
insert into MENU_CATEGORY (category_id, category_name, description) values (96, 'Baking Ingredients 96', 'Adaptive 24/7 matrix');
insert into MENU_CATEGORY (category_id, category_name, description) values (97, 'Salad Kits 97', 'Profound mission-critical challenge');
insert into MENU_CATEGORY (category_id, category_name, description) values (98, 'Healthy Snacks 98', 'Integrated user-facing success');
insert into MENU_CATEGORY (category_id, category_name, description) values (99, 'Healthy Snacks 99', 'Streamlined radical product');
insert into MENU_CATEGORY (category_id, category_name, description) values (100, 'Outdoor Footwear 100', 'Adaptive mission-critical website');
insert into MENU_CATEGORY (category_id, category_name, description) values (101, 'BBQ Sauces 101', 'Programmable reciprocal moderator');
insert into MENU_CATEGORY (category_id, category_name, description) values (102, 'Emergency Preparedness & First Aid 102', 'Optional stable budgetary management');
insert into MENU_CATEGORY (category_id, category_name, description) values (103, 'Pasta Sauces 103', 'Exclusive 6th generation process improvement');
insert into MENU_CATEGORY (category_id, category_name, description) values (104, 'Phone Accessories 104', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (105, 'Aromatherapy & Wellness 105', 'Organic logistical moratorium');
insert into MENU_CATEGORY (category_id, category_name, description) values (106, 'Home Organization 106', 'Reduced modular local area network');
insert into MENU_CATEGORY (category_id, category_name, description) values (107, 'Baking Accessories 107', 'Synergized eco-centric firmware');
insert into MENU_CATEGORY (category_id, category_name, description) values (108, 'BBQ Sauces 108', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (109, 'Candy 109', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (110, 'Hats & Headwear 110', 'Compatible object-oriented success');
insert into MENU_CATEGORY (category_id, category_name, description) values (111, 'Seasoning Blends 111', 'Operative 3rd generation complexity');
insert into MENU_CATEGORY (category_id, category_name, description) values (112, 'Outdoor Accessories 112', 'Re-engineered 24 hour collaboration');
insert into MENU_CATEGORY (category_id, category_name, description) values (113, 'Frozen Snacks 113', 'Expanded multimedia access');
insert into MENU_CATEGORY (category_id, category_name, description) values (114, 'Hydration Gear 114', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (115, 'Jackets 115', 'Multi-channelled reciprocal database');
insert into MENU_CATEGORY (category_id, category_name, description) values (116, 'Personal Care & Grooming 116', 'Cloned background support');
insert into MENU_CATEGORY (category_id, category_name, description) values (117, 'Frozen Pizza 117', 'Exclusive demand-driven toolset');
insert into MENU_CATEGORY (category_id, category_name, description) values (118, 'Frozen Meals 118', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (119, 'Small Appliances 119', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (120, 'Graphic Tees 120', 'Devolved dedicated emulation');
insert into MENU_CATEGORY (category_id, category_name, description) values (121, 'Office Supplies 121', 'Quality-focused contextually-based circuit');
insert into MENU_CATEGORY (category_id, category_name, description) values (122, 'Health Devices 122', 'Stand-alone methodical groupware');
insert into MENU_CATEGORY (category_id, category_name, description) values (123, 'Grooming Supplies 123', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (124, 'Outdoor Accessories 124', 'Ameliorated static leverage');
insert into MENU_CATEGORY (category_id, category_name, description) values (125, 'Specialty Grains 125', 'Multi-channelled bifurcated process improvement');
insert into MENU_CATEGORY (category_id, category_name, description) values (126, 'Home Organization 126', 'Ergonomic encompassing paradigm');
insert into MENU_CATEGORY (category_id, category_name, description) values (127, 'Kitchen Storage & Organization 127', 'Synchronised web-enabled success');
insert into MENU_CATEGORY (category_id, category_name, description) values (128, 'Small Appliances 128', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (129, 'Specialty Pasta 129', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (130, 'Soups & Broths 130', 'Stand-alone homogeneous middleware');
insert into MENU_CATEGORY (category_id, category_name, description) values (131, 'Board Games 131', 'Customer-focused bottom-line interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (132, 'Home Fragrance & Accessories 132', 'Innovative homogeneous Graphical User Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (133, 'Vegetables 133', 'Universal system-worthy project');
insert into MENU_CATEGORY (category_id, category_name, description) values (134, 'Ice Cream 134', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (135, 'Nut Butters 135', 'Organic real-time functionalities');
insert into MENU_CATEGORY (category_id, category_name, description) values (136, 'Coffee 136', 'Future-proofed 24/7 forecast');
insert into MENU_CATEGORY (category_id, category_name, description) values (137, 'Seasoning Blends 137', 'Optimized bi-directional methodology');
insert into MENU_CATEGORY (category_id, category_name, description) values (138, 'Rice Dishes 138', 'Profound motivating product');
insert into MENU_CATEGORY (category_id, category_name, description) values (139, 'Home Security 139', 'User-centric value-added encryption');
insert into MENU_CATEGORY (category_id, category_name, description) values (140, 'Audio Accessories 140', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (141, 'Herbal Tea 141', 'Quality-focused context-sensitive encryption');
insert into MENU_CATEGORY (category_id, category_name, description) values (142, 'Spicy Sauces 142', 'Progressive 4th generation synergy');
insert into MENU_CATEGORY (category_id, category_name, description) values (143, 'Outdoor Play Toys 143', 'Versatile real-time Graphic Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (144, 'Outerwear 144', 'Automated grid-enabled firmware');
insert into MENU_CATEGORY (category_id, category_name, description) values (145, 'Office Accessories 145', 'Universal didactic synergy');
insert into MENU_CATEGORY (category_id, category_name, description) values (146, 'Frozen Vegetables 146', 'Reactive encompassing knowledge user');
insert into MENU_CATEGORY (category_id, category_name, description) values (147, 'Mustards 147', 'Extended eco-centric collaboration');
insert into MENU_CATEGORY (category_id, category_name, description) values (148, 'Rice 148', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (149, 'Educational Toys 149', 'Devolved disintermediate initiative');
insert into MENU_CATEGORY (category_id, category_name, description) values (150, 'Pasta 150', 'Devolved radical parallelism');
insert into MENU_CATEGORY (category_id, category_name, description) values (151, 'Mobile Accessories 151', 'Operative executive implementation');
insert into MENU_CATEGORY (category_id, category_name, description) values (152, 'Fruit Spreads 152', 'Synergistic solution-oriented standardization');
insert into MENU_CATEGORY (category_id, category_name, description) values (153, 'Specialty Pasta 153', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (154, 'Outdoor Apparel 154', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (155, 'Healthy Snacks 155', 'User-friendly intermediate internet solution');
insert into MENU_CATEGORY (category_id, category_name, description) values (156, 'Sustainable Fashion 156', 'Public-key mission-critical installation');
insert into MENU_CATEGORY (category_id, category_name, description) values (157, 'Vegetarian Soups 157', 'Ergonomic human-resource array');
insert into MENU_CATEGORY (category_id, category_name, description) values (158, 'Strength Training Equipment 158', 'Devolved zero administration paradigm');
insert into MENU_CATEGORY (category_id, category_name, description) values (159, 'Wireless Video Transmission 159', 'Advanced next generation flexibility');
insert into MENU_CATEGORY (category_id, category_name, description) values (160, 'Travel Accessories 160', 'Re-engineered well-modulated project');
insert into MENU_CATEGORY (category_id, category_name, description) values (161, 'Ice Cream Flavors 161', 'Mandatory neutral focus group');
insert into MENU_CATEGORY (category_id, category_name, description) values (162, 'Salsas 162', 'Organized web-enabled installation');
insert into MENU_CATEGORY (category_id, category_name, description) values (163, 'Drinkware 163', 'Visionary global contingency');
insert into MENU_CATEGORY (category_id, category_name, description) values (164, 'Eyewear 164', 'Inverse clear-thinking installation');
insert into MENU_CATEGORY (category_id, category_name, description) values (165, 'Cooking Tools & Utensils 165', 'Universal explicit frame');
insert into MENU_CATEGORY (category_id, category_name, description) values (166, 'Coffee Creamers 166', 'Re-contextualized attitude-oriented model');
insert into MENU_CATEGORY (category_id, category_name, description) values (167, 'Processed Meats 167', 'Sharable value-added Graphic Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (168, 'Herbal Tea 168', 'Intuitive value-added data-warehouse');
insert into MENU_CATEGORY (category_id, category_name, description) values (169, 'Specialty Cheeses 169', 'Re-contextualized upward-trending contingency');
insert into MENU_CATEGORY (category_id, category_name, description) values (170, 'Salad Mixes 170', 'Persistent 3rd generation policy');
insert into MENU_CATEGORY (category_id, category_name, description) values (171, 'Spice Blends 171', 'Monitored tangible circuit');
insert into MENU_CATEGORY (category_id, category_name, description) values (172, 'Health Devices 172', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (173, 'Asian Sauces 173', 'Business-focused needs-based implementation');
insert into MENU_CATEGORY (category_id, category_name, description) values (174, 'Recovery Tools 174', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (175, 'Frozen Vegan Meals 175', 'Cross-platform tangible encryption');
insert into MENU_CATEGORY (category_id, category_name, description) values (176, 'Activewear Jackets 176', 'Programmable clear-thinking emulation');
insert into MENU_CATEGORY (category_id, category_name, description) values (177, 'Office Accessories 177', 'Switchable full-range strategy');
insert into MENU_CATEGORY (category_id, category_name, description) values (178, 'Home Entertainment Equipment 178', 'Open-source web-enabled installation');
insert into MENU_CATEGORY (category_id, category_name, description) values (179, 'Coffee 179', 'Reverse-engineered radical productivity');
insert into MENU_CATEGORY (category_id, category_name, description) values (180, 'Home Organization 180', 'Ameliorated grid-enabled capacity');
insert into MENU_CATEGORY (category_id, category_name, description) values (181, 'Dry Sauces 181', 'Focused impactful emulation');
insert into MENU_CATEGORY (category_id, category_name, description) values (182, 'Bedding & Linens 182', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (183, 'Camping Equipment 183', 'Pre-emptive upward-trending model');
insert into MENU_CATEGORY (category_id, category_name, description) values (184, 'Grooming Supplies 184', 'Advanced 6th generation neural-net');
insert into MENU_CATEGORY (category_id, category_name, description) values (185, 'Bedding & Linens 185', 'Inverse regional hardware');
insert into MENU_CATEGORY (category_id, category_name, description) values (186, 'Painting Supplies 186', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (187, 'Dishwashers 187', 'Horizontal discrete database');
insert into MENU_CATEGORY (category_id, category_name, description) values (188, 'Strength Training Equipment 188', 'Team-oriented contextually-based contingency');
insert into MENU_CATEGORY (category_id, category_name, description) values (189, 'Grooming Supplies 189', 'Centralized 3rd generation intranet');
insert into MENU_CATEGORY (category_id, category_name, description) values (190, 'Coffee Accessories 190', 'De-engineered context-sensitive leverage');
insert into MENU_CATEGORY (category_id, category_name, description) values (191, 'Travel Accessories 191', 'Streamlined maximized initiative');
insert into MENU_CATEGORY (category_id, category_name, description) values (192, 'Indoor Gardening Kits 192', 'Advanced zero administration orchestration');
insert into MENU_CATEGORY (category_id, category_name, description) values (193, 'Grains 193', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (194, 'Healthy Snacks 194', 'Face to face even-keeled open system');
insert into MENU_CATEGORY (category_id, category_name, description) values (195, 'Makeup 195', 'Sharable transitional encoding');
insert into MENU_CATEGORY (category_id, category_name, description) values (196, 'Breads 196', 'Fully-configurable content-based throughput');
insert into MENU_CATEGORY (category_id, category_name, description) values (197, 'Educational Toys 197', 'Innovative analyzing migration');
insert into MENU_CATEGORY (category_id, category_name, description) values (198, 'Whole Grain Breads 198', 'Team-oriented 4th generation standardization');
insert into MENU_CATEGORY (category_id, category_name, description) values (199, 'Healthy Snacks 199', 'Future-proofed bifurcated knowledge user');
insert into MENU_CATEGORY (category_id, category_name, description) values (200, 'Cutting Boards & Utensils 200', 'Synergized stable help-desk');
insert into MENU_CATEGORY (category_id, category_name, description) values (201, 'Savory Snacks 201', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (202, 'Dairy Spreads 202', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (203, 'Outerwear - Faux Fur 203', 'Compatible bifurcated attitude');
insert into MENU_CATEGORY (category_id, category_name, description) values (204, 'Meat Snacks 204', 'Robust real-time instruction set');
insert into MENU_CATEGORY (category_id, category_name, description) values (205, 'Grooming Supplies 205', 'Open-source homogeneous capability');
insert into MENU_CATEGORY (category_id, category_name, description) values (206, 'Bedding & Linens 206', 'Secured multi-tasking portal');
insert into MENU_CATEGORY (category_id, category_name, description) values (207, 'Cheese 207', 'Quality-focused coherent complexity');
insert into MENU_CATEGORY (category_id, category_name, description) values (208, 'Savory Snacks 208', 'Expanded real-time superstructure');
insert into MENU_CATEGORY (category_id, category_name, description) values (209, 'Specialty Pasta 209', 'Future-proofed leading edge implementation');
insert into MENU_CATEGORY (category_id, category_name, description) values (210, 'Savory Nuts 210', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (211, 'Herb-Based Sauces 211', 'Implemented exuding synergy');
insert into MENU_CATEGORY (category_id, category_name, description) values (212, 'Granola/Cereal 212', 'Persevering maximized workforce');
insert into MENU_CATEGORY (category_id, category_name, description) values (213, 'Dog Accessories 213', 'Adaptive value-added function');
insert into MENU_CATEGORY (category_id, category_name, description) values (214, 'Soups & Broths 214', 'Reactive upward-trending contingency');
insert into MENU_CATEGORY (category_id, category_name, description) values (215, 'Healthy Snacks 215', 'Customizable object-oriented info-mediaries');
insert into MENU_CATEGORY (category_id, category_name, description) values (216, 'Vegetables 216', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (217, 'Guacamole 217', 'Cross-platform holistic access');
insert into MENU_CATEGORY (category_id, category_name, description) values (218, 'Drinkware 218', 'De-engineered neutral infrastructure');
insert into MENU_CATEGORY (category_id, category_name, description) values (219, 'Home Organization 219', 'Monitored demand-driven system engine');
insert into MENU_CATEGORY (category_id, category_name, description) values (220, 'Fruit Spreads 220', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (221, 'Fruit Spreads 221', 'Optimized motivating help-desk');
insert into MENU_CATEGORY (category_id, category_name, description) values (222, 'Drinkware 222', 'Triple-buffered systemic challenge');
insert into MENU_CATEGORY (category_id, category_name, description) values (223, 'Athletic Footwear 223', 'Upgradable disintermediate standardization');
insert into MENU_CATEGORY (category_id, category_name, description) values (224, 'Cooking Tools & Utensils 224', 'Synchronised attitude-oriented Graphical User Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (225, 'Frozen Meals 225', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (226, 'Poultry 226', 'Seamless multimedia superstructure');
insert into MENU_CATEGORY (category_id, category_name, description) values (227, 'Air Quality & Purification 227', 'Diverse even-keeled toolset');
insert into MENU_CATEGORY (category_id, category_name, description) values (228, 'Cookbooks & Nutrition 228', 'Diverse 24/7 budgetary management');
insert into MENU_CATEGORY (category_id, category_name, description) values (229, 'Health Devices 229', 'Public-key grid-enabled capacity');
insert into MENU_CATEGORY (category_id, category_name, description) values (230, 'Chips and Crisps 230', 'Realigned human-resource firmware');
insert into MENU_CATEGORY (category_id, category_name, description) values (231, 'Indoor Gardening Kits 231', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (232, 'Smart Home & Security 232', 'Public-key tangible instruction set');
insert into MENU_CATEGORY (category_id, category_name, description) values (233, 'Educational Toys 233', 'Organized actuating database');
insert into MENU_CATEGORY (category_id, category_name, description) values (234, 'Frozen Baked Goods 234', 'Stand-alone hybrid workforce');
insert into MENU_CATEGORY (category_id, category_name, description) values (235, 'Coffee Equipment 235', 'Innovative encompassing frame');
insert into MENU_CATEGORY (category_id, category_name, description) values (236, 'Bedding & Linens 236', 'Diverse 5th generation array');
insert into MENU_CATEGORY (category_id, category_name, description) values (237, 'Fresh Mushrooms 237', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (238, 'Injury Prevention & Recovery 238', 'Universal bandwidth-monitored collaboration');
insert into MENU_CATEGORY (category_id, category_name, description) values (239, 'Home Decor 239', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (240, 'Sustainable Fashion 240', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (241, 'Educational Toys 241', 'Pre-emptive tertiary hardware');
insert into MENU_CATEGORY (category_id, category_name, description) values (242, 'Whole Grains 242', 'Multi-channelled composite budgetary management');
insert into MENU_CATEGORY (category_id, category_name, description) values (243, 'Watches 243', 'Function-based user-facing moratorium');
insert into MENU_CATEGORY (category_id, category_name, description) values (244, 'Cooking Appliances 244', 'Diverse zero tolerance solution');
insert into MENU_CATEGORY (category_id, category_name, description) values (245, 'Office Supplies 245', 'Fundamental didactic framework');
insert into MENU_CATEGORY (category_id, category_name, description) values (246, 'Dress Shirts 246', 'Enhanced well-modulated capability');
insert into MENU_CATEGORY (category_id, category_name, description) values (247, 'Eggs 247', 'Multi-layered composite architecture');
insert into MENU_CATEGORY (category_id, category_name, description) values (248, 'Massage Therapy 248', 'Focused tangible access');
insert into MENU_CATEGORY (category_id, category_name, description) values (249, 'Salad Kits 249', 'Customer-focused exuding analyzer');
insert into MENU_CATEGORY (category_id, category_name, description) values (250, 'Educational Toys 250', 'Polarised asynchronous implementation');
insert into MENU_CATEGORY (category_id, category_name, description) values (251, 'Baking Accessories 251', 'Configurable transitional encryption');
insert into MENU_CATEGORY (category_id, category_name, description) values (252, 'Dried Fruits 252', 'Ergonomic user-facing pricing structure');
insert into MENU_CATEGORY (category_id, category_name, description) values (253, 'Barware 253', 'Synergized intermediate utilisation');
insert into MENU_CATEGORY (category_id, category_name, description) values (254, 'Snacks 254', 'Grass-roots didactic firmware');
insert into MENU_CATEGORY (category_id, category_name, description) values (255, 'Decorative Wall Art & Accessories 255', 'Secured intermediate standardization');
insert into MENU_CATEGORY (category_id, category_name, description) values (256, 'Pasta Sauces 256', 'Configurable 6th generation parallelism');
insert into MENU_CATEGORY (category_id, category_name, description) values (257, 'Salsas & Dips 257', 'Upgradable optimal access');
insert into MENU_CATEGORY (category_id, category_name, description) values (258, 'Garden Tools 258', 'Organic actuating methodology');
insert into MENU_CATEGORY (category_id, category_name, description) values (259, 'Grilling Accessories 259', 'Up-sized exuding strategy');
insert into MENU_CATEGORY (category_id, category_name, description) values (260, 'Frozen Seafood 260', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (261, 'Dips & Spreads 261', 'Inverse upward-trending contingency');
insert into MENU_CATEGORY (category_id, category_name, description) values (262, 'Wireless Audio Accessories 262', 'Balanced contextually-based matrices');
insert into MENU_CATEGORY (category_id, category_name, description) values (263, 'Fitness Accessories 263', 'Mandatory secondary strategy');
insert into MENU_CATEGORY (category_id, category_name, description) values (264, 'Solar Power Accessories 264', 'Automated attitude-oriented project');
insert into MENU_CATEGORY (category_id, category_name, description) values (265, 'Processed Meats 265', 'Pre-emptive bifurcated solution');
insert into MENU_CATEGORY (category_id, category_name, description) values (266, 'Savory Snacks 266', 'Seamless leading edge paradigm');
insert into MENU_CATEGORY (category_id, category_name, description) values (267, 'Barware 267', 'Configurable zero tolerance secured line');
insert into MENU_CATEGORY (category_id, category_name, description) values (268, 'Pasta 268', 'Distributed clear-thinking strategy');
insert into MENU_CATEGORY (category_id, category_name, description) values (269, 'Salads 269', 'Stand-alone holistic hierarchy');
insert into MENU_CATEGORY (category_id, category_name, description) values (270, 'Travel Accessories 270', 'Innovative needs-based portal');
insert into MENU_CATEGORY (category_id, category_name, description) values (271, 'Specialty Pasta 271', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (272, 'Garden Tools 272', 'Self-enabling maximized protocol');
insert into MENU_CATEGORY (category_id, category_name, description) values (273, 'Granola 273', 'Distributed fresh-thinking encoding');
insert into MENU_CATEGORY (category_id, category_name, description) values (274, 'Storage Devices 274', 'Phased analyzing monitoring');
insert into MENU_CATEGORY (category_id, category_name, description) values (275, 'Mustards 275', 'Optimized reciprocal customer loyalty');
insert into MENU_CATEGORY (category_id, category_name, description) values (276, 'Outdoor Recreation 276', 'Function-based full-range Graphic Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (277, 'Juice 277', 'Mandatory 4th generation service-desk');
insert into MENU_CATEGORY (category_id, category_name, description) values (278, 'Food Storage Solutions 278', 'Automated maximized instruction set');
insert into MENU_CATEGORY (category_id, category_name, description) values (279, 'Poultry 279', 'Reactive disintermediate interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (280, 'Miniature Sports Games 280', 'Persistent zero defect matrices');
insert into MENU_CATEGORY (category_id, category_name, description) values (281, 'Coffee Accessories 281', 'Devolved multimedia orchestration');
insert into MENU_CATEGORY (category_id, category_name, description) values (282, 'Regional Seasoning Blends 282', 'Synergized modular support');
insert into MENU_CATEGORY (category_id, category_name, description) values (283, 'Meal Kits 283', 'Quality-focused even-keeled matrices');
insert into MENU_CATEGORY (category_id, category_name, description) values (284, 'Health Devices 284', 'Persevering background circuit');
insert into MENU_CATEGORY (category_id, category_name, description) values (285, 'Potatoes 285', 'Open-source tangible firmware');
insert into MENU_CATEGORY (category_id, category_name, description) values (286, 'Pancake and Waffle Mixes 286', 'Persistent transitional task-force');
insert into MENU_CATEGORY (category_id, category_name, description) values (287, 'Frozen Vegetarian Meals 287', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (288, 'Camping Equipment 288', 'Horizontal contextually-based functionalities');
insert into MENU_CATEGORY (category_id, category_name, description) values (289, 'Vegetables 289', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (290, 'Vegetables 290', 'Vision-oriented impactful matrices');
insert into MENU_CATEGORY (category_id, category_name, description) values (291, 'Athletic Footwear 291', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (292, 'Meat Products 292', 'Front-line eco-centric attitude');
insert into MENU_CATEGORY (category_id, category_name, description) values (293, 'Outdoor Play Toys 293', 'Managed stable architecture');
insert into MENU_CATEGORY (category_id, category_name, description) values (294, 'Grooming 294', 'Upgradable didactic methodology');
insert into MENU_CATEGORY (category_id, category_name, description) values (295, 'Cardio Equipment 295', 'Operative zero tolerance budgetary management');
insert into MENU_CATEGORY (category_id, category_name, description) values (296, 'Fruits 296', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (297, 'Bean Salads 297', 'Sharable intermediate benchmark');
insert into MENU_CATEGORY (category_id, category_name, description) values (298, 'Nuts and Trail Mix 298', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (299, 'Tech Accessories 299', 'Business-focused client-server matrices');
insert into MENU_CATEGORY (category_id, category_name, description) values (300, 'Fitness Accessories 300', 'Robust well-modulated model');
insert into MENU_CATEGORY (category_id, category_name, description) values (301, 'Garden Tools 301', 'Balanced upward-trending knowledge user');
insert into MENU_CATEGORY (category_id, category_name, description) values (302, 'Car Cleaning 302', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (303, 'Dried Fruits 303', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (304, 'Baking Accessories 304', 'Optimized interactive approach');
insert into MENU_CATEGORY (category_id, category_name, description) values (305, 'Furniture 305', 'Customer-focused coherent Graphical User Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (306, 'Dinnerware 306', 'Function-based fault-tolerant internet solution');
insert into MENU_CATEGORY (category_id, category_name, description) values (307, ' smoothies 307', 'Function-based needs-based forecast');
insert into MENU_CATEGORY (category_id, category_name, description) values (308, 'Baking Ingredients 308', 'Programmable attitude-oriented solution');
insert into MENU_CATEGORY (category_id, category_name, description) values (309, 'Pasta Alternatives 309', 'Pre-emptive zero tolerance function');
insert into MENU_CATEGORY (category_id, category_name, description) values (310, 'Fruit Spreads 310', 'Horizontal systematic forecast');
insert into MENU_CATEGORY (category_id, category_name, description) values (311, 'Garden Tools 311', 'Versatile impactful matrices');
insert into MENU_CATEGORY (category_id, category_name, description) values (312, 'Nut Snacks 312', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (313, 'Healthy Snacks 313', 'Realigned multimedia project');
insert into MENU_CATEGORY (category_id, category_name, description) values (314, 'Frozen Seafood 314', 'Stand-alone 3rd generation neural-net');
insert into MENU_CATEGORY (category_id, category_name, description) values (315, 'Breads 315', 'Virtual static service-desk');
insert into MENU_CATEGORY (category_id, category_name, description) values (316, 'Outdoor Accessories 316', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (317, 'Small Appliances 317', 'Devolved impactful focus group');
insert into MENU_CATEGORY (category_id, category_name, description) values (318, 'Canned Legumes 318', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (319, 'Vegetarian Meals 319', 'Profit-focused contextually-based Graphical User Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (320, 'Dressing 320', 'Assimilated multimedia process improvement');
insert into MENU_CATEGORY (category_id, category_name, description) values (321, 'Plant-Based Beverages 321', 'Virtual fresh-thinking portal');
insert into MENU_CATEGORY (category_id, category_name, description) values (322, 'Fitness & Nutrition 322', 'Diverse 24/7 capacity');
insert into MENU_CATEGORY (category_id, category_name, description) values (323, 'Plant-Based Yogurt 323', 'Mandatory coherent knowledge user');
insert into MENU_CATEGORY (category_id, category_name, description) values (324, 'Drinkware 324', 'Visionary homogeneous benchmark');
insert into MENU_CATEGORY (category_id, category_name, description) values (325, 'Tea 325', 'Fundamental systematic website');
insert into MENU_CATEGORY (category_id, category_name, description) values (326, 'Dips and Spreads 326', 'Upgradable dynamic knowledge user');
insert into MENU_CATEGORY (category_id, category_name, description) values (327, 'Vegetables 327', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (328, 'Cooking Oils 328', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (329, 'Poultry 329', 'Re-engineered web-enabled hub');
insert into MENU_CATEGORY (category_id, category_name, description) values (330, 'Outdoor Accessories 330', 'Business-focused impactful moratorium');
insert into MENU_CATEGORY (category_id, category_name, description) values (331, 'Cooking Tools & Utensils 331', 'Public-key bifurcated implementation');
insert into MENU_CATEGORY (category_id, category_name, description) values (332, 'Bags 332', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (333, 'Salsas 333', 'Networked well-modulated Graphic Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (334, 'Healthy Desserts 334', 'Total scalable attitude');
insert into MENU_CATEGORY (category_id, category_name, description) values (335, 'Frozen Asian Meals 335', 'Devolved mission-critical algorithm');
insert into MENU_CATEGORY (category_id, category_name, description) values (336, 'Vegetarian Meals 336', 'Profit-focused fresh-thinking hub');
insert into MENU_CATEGORY (category_id, category_name, description) values (337, 'Coffee Accessories 337', 'Implemented foreground attitude');
insert into MENU_CATEGORY (category_id, category_name, description) values (338, 'Dried Fruits 338', 'User-centric eco-centric migration');
insert into MENU_CATEGORY (category_id, category_name, description) values (339, 'Car Cleaning 339', 'Adaptive even-keeled projection');
insert into MENU_CATEGORY (category_id, category_name, description) values (340, 'Outerwear 340', 'Fundamental secondary function');
insert into MENU_CATEGORY (category_id, category_name, description) values (341, 'Outdoor Recreation 341', 'Synchronised multimedia alliance');
insert into MENU_CATEGORY (category_id, category_name, description) values (342, 'Wine Accessories 342', 'Robust holistic complexity');
insert into MENU_CATEGORY (category_id, category_name, description) values (343, 'Outdoor Play Toys 343', 'Sharable mission-critical intranet');
insert into MENU_CATEGORY (category_id, category_name, description) values (344, 'Breads 344', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (345, 'Salsas and Dips 345', 'Optional background firmware');
insert into MENU_CATEGORY (category_id, category_name, description) values (346, 'Cookies 346', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (347, 'Pet Accessories 347', 'Proactive attitude-oriented benchmark');
insert into MENU_CATEGORY (category_id, category_name, description) values (348, 'Soups & Broths 348', 'Reverse-engineered homogeneous array');
insert into MENU_CATEGORY (category_id, category_name, description) values (349, 'Cleaning Supplies 349', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (350, 'Jackets 350', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (351, 'Pain Relief 351', 'Exclusive tangible success');
insert into MENU_CATEGORY (category_id, category_name, description) values (352, 'Car Cleaning 352', 'Customizable asymmetric Graphical User Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (353, 'Cooking Tools & Utensils 353', 'Adaptive cohesive extranet');
insert into MENU_CATEGORY (category_id, category_name, description) values (354, 'Garden Supplies 354', 'Devolved dedicated parallelism');
insert into MENU_CATEGORY (category_id, category_name, description) values (355, 'Italian Cuisine 355', 'Horizontal content-based hardware');
insert into MENU_CATEGORY (category_id, category_name, description) values (356, 'Garden Tools 356', 'Universal discrete local area network');
insert into MENU_CATEGORY (category_id, category_name, description) values (357, 'Self-Defense Tools 357', 'Reactive asymmetric model');
insert into MENU_CATEGORY (category_id, category_name, description) values (358, 'Training Supplies 358', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (359, 'Salads 359', 'Cloned bottom-line Graphical User Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (360, 'Kitchen Gadgets 360', 'Future-proofed explicit function');
insert into MENU_CATEGORY (category_id, category_name, description) values (361, 'Healthy Snacks 361', 'Customizable interactive success');
insert into MENU_CATEGORY (category_id, category_name, description) values (362, 'Nut-Based Snacks 362', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (363, 'Hydration Gear 363', 'Multi-lateral stable interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (364, 'Plant-Based Proteins 364', 'Right-sized 6th generation matrices');
insert into MENU_CATEGORY (category_id, category_name, description) values (365, 'Canned Fruits 365', 'Re-engineered global artificial intelligence');
insert into MENU_CATEGORY (category_id, category_name, description) values (366, 'Candle & Soap Making Supplies 366', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (367, 'Fruit Spreads 367', 'Universal neutral function');
insert into MENU_CATEGORY (category_id, category_name, description) values (368, 'Food Storage Solutions 368', 'Robust discrete infrastructure');
insert into MENU_CATEGORY (category_id, category_name, description) values (369, 'Hydration Gear 369', 'Multi-layered composite complexity');
insert into MENU_CATEGORY (category_id, category_name, description) values (370, 'Savory Snacks 370', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (371, 'Small Appliances 371', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (372, 'Poultry 372', 'Reduced uniform groupware');
insert into MENU_CATEGORY (category_id, category_name, description) values (373, 'Granola/Cereal 373', 'Object-based upward-trending concept');
insert into MENU_CATEGORY (category_id, category_name, description) values (374, 'Camping Equipment 374', 'Persevering global encoding');
insert into MENU_CATEGORY (category_id, category_name, description) values (375, 'Wine Accessories 375', 'Exclusive didactic interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (376, 'Watches 376', 'Multi-channelled global paradigm');
insert into MENU_CATEGORY (category_id, category_name, description) values (377, 'Frozen Vegetable Dishes 377', 'Proactive even-keeled policy');
insert into MENU_CATEGORY (category_id, category_name, description) values (378, 'Sauces 378', 'Total secondary flexibility');
insert into MENU_CATEGORY (category_id, category_name, description) values (379, 'Journals 379', 'Cloned methodical parallelism');
insert into MENU_CATEGORY (category_id, category_name, description) values (380, 'Lighting 380', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (381, 'Chewy Candies 381', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (382, 'Small Appliances 382', 'Intuitive upward-trending initiative');
insert into MENU_CATEGORY (category_id, category_name, description) values (383, 'Poultry 383', 'Fully-configurable fault-tolerant synergy');
insert into MENU_CATEGORY (category_id, category_name, description) values (384, 'Creative Toys 384', 'Digitized uniform Graphic Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (385, 'Audio Recording Devices 385', 'Multi-channelled needs-based moderator');
insert into MENU_CATEGORY (category_id, category_name, description) values (386, 'Plant-Based Meals 386', 'Monitored zero defect firmware');
insert into MENU_CATEGORY (category_id, category_name, description) values (387, 'Personal Care & Grooming 387', 'Multi-layered demand-driven collaboration');
insert into MENU_CATEGORY (category_id, category_name, description) values (388, 'Salsas 388', 'Polarised systematic implementation');
insert into MENU_CATEGORY (category_id, category_name, description) values (389, 'Smart Home & Security 389', 'Horizontal even-keeled hub');
insert into MENU_CATEGORY (category_id, category_name, description) values (390, 'Camping Equipment 390', 'Ergonomic demand-driven synergy');
insert into MENU_CATEGORY (category_id, category_name, description) values (391, 'Decorative Wall Art & Accessories 391', 'Focused object-oriented orchestration');
insert into MENU_CATEGORY (category_id, category_name, description) values (392, 'Car Cleaning 392', 'Mandatory scalable attitude');
insert into MENU_CATEGORY (category_id, category_name, description) values (393, 'Grooming Supplies 393', 'Integrated incremental installation');
insert into MENU_CATEGORY (category_id, category_name, description) values (394, 'Home Organization 394', 'Self-enabling attitude-oriented database');
insert into MENU_CATEGORY (category_id, category_name, description) values (395, 'Home Appliances 395', 'Synergized 3rd generation architecture');
insert into MENU_CATEGORY (category_id, category_name, description) values (396, 'Mixes 396', 'Decentralized 4th generation standardization');
insert into MENU_CATEGORY (category_id, category_name, description) values (397, 'Frozen Vegetables 397', 'Robust fault-tolerant service-desk');
insert into MENU_CATEGORY (category_id, category_name, description) values (398, 'Camping Equipment 398', 'Networked asymmetric conglomeration');
insert into MENU_CATEGORY (category_id, category_name, description) values (399, 'Lighting & Lamps 399', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (400, 'Travel Accessories 400', 'Universal object-oriented Graphic Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (401, 'Cardio Equipment 401', 'Streamlined asynchronous moderator');
insert into MENU_CATEGORY (category_id, category_name, description) values (402, 'Wraps and Flatbreads 402', 'Open-architected object-oriented instruction set');
insert into MENU_CATEGORY (category_id, category_name, description) values (403, 'Garden Decor 403', 'Diverse solution-oriented Graphic Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (404, 'Chocolate Desserts 404', 'Profit-focused secondary groupware');
insert into MENU_CATEGORY (category_id, category_name, description) values (405, 'Aromatherapy & Wellness 405', 'Profound eco-centric task-force');
insert into MENU_CATEGORY (category_id, category_name, description) values (406, 'Frozen Meals 406', 'Customer-focused directional system engine');
insert into MENU_CATEGORY (category_id, category_name, description) values (407, 'Vegetables 407', 'Decentralized systemic service-desk');
insert into MENU_CATEGORY (category_id, category_name, description) values (408, 'Granola 408', 'Focused multi-tasking frame');
insert into MENU_CATEGORY (category_id, category_name, description) values (409, 'Shirts 409', 'Exclusive background toolset');
insert into MENU_CATEGORY (category_id, category_name, description) values (410, 'Cheese Spreads 410', 'Diverse coherent capability');
insert into MENU_CATEGORY (category_id, category_name, description) values (411, 'Karaoke Equipment 411', 'Automated systemic extranet');
insert into MENU_CATEGORY (category_id, category_name, description) values (412, 'Fresh Cut Vegetables 412', 'Mandatory client-driven task-force');
insert into MENU_CATEGORY (category_id, category_name, description) values (413, 'Personal Care & Grooming 413', 'Distributed leading edge array');
insert into MENU_CATEGORY (category_id, category_name, description) values (414, 'Computer Accessories 414', 'Configurable mobile collaboration');
insert into MENU_CATEGORY (category_id, category_name, description) values (415, 'Cameras & Photography 415', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (416, 'Cutting Boards & Utensils 416', 'Progressive homogeneous leverage');
insert into MENU_CATEGORY (category_id, category_name, description) values (417, 'Health & Wellness Tools 417', 'Cross-group leading edge analyzer');
insert into MENU_CATEGORY (category_id, category_name, description) values (418, 'Sauces 418', 'Innovative directional protocol');
insert into MENU_CATEGORY (category_id, category_name, description) values (419, 'Food Storage Solutions 419', 'Networked zero tolerance workforce');
insert into MENU_CATEGORY (category_id, category_name, description) values (420, 'Cookies 420', 'Grass-roots content-based solution');
insert into MENU_CATEGORY (category_id, category_name, description) values (421, 'Team Sports 421', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (422, 'Vegetable Dishes 422', 'Total reciprocal collaboration');
insert into MENU_CATEGORY (category_id, category_name, description) values (423, 'Journals 423', 'Triple-buffered heuristic strategy');
insert into MENU_CATEGORY (category_id, category_name, description) values (424, 'Training Supplies 424', 'Quality-focused solution-oriented architecture');
insert into MENU_CATEGORY (category_id, category_name, description) values (425, 'Vegan Baked Goods 425', 'Persevering eco-centric flexibility');
insert into MENU_CATEGORY (category_id, category_name, description) values (426, 'Hot Sauces 426', 'Extended even-keeled capacity');
insert into MENU_CATEGORY (category_id, category_name, description) values (427, 'Healthy Snacks 427', 'Implemented bottom-line emulation');
insert into MENU_CATEGORY (category_id, category_name, description) values (428, 'Smart Lighting 428', 'Versatile bottom-line customer loyalty');
insert into MENU_CATEGORY (category_id, category_name, description) values (429, 'Dips and Spreads 429', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (430, 'Camping Equipment 430', 'Stand-alone maximized challenge');
insert into MENU_CATEGORY (category_id, category_name, description) values (431, 'Camping Equipment 431', 'Robust contextually-based challenge');
insert into MENU_CATEGORY (category_id, category_name, description) values (432, 'Smoothies 432', 'Customizable coherent open system');
insert into MENU_CATEGORY (category_id, category_name, description) values (433, 'Formal Pants 433', 'Enhanced coherent superstructure');
insert into MENU_CATEGORY (category_id, category_name, description) values (434, 'Kitchen Accessories 434', 'Reactive optimal complexity');
insert into MENU_CATEGORY (category_id, category_name, description) values (435, 'Poultry 435', 'Cloned hybrid groupware');
insert into MENU_CATEGORY (category_id, category_name, description) values (436, 'Camping Equipment 436', 'Programmable logistical system engine');
insert into MENU_CATEGORY (category_id, category_name, description) values (437, 'Home Organization 437', 'Horizontal asymmetric product');
insert into MENU_CATEGORY (category_id, category_name, description) values (438, 'Travel Accessories 438', 'Up-sized needs-based protocol');
insert into MENU_CATEGORY (category_id, category_name, description) values (439, 'Baking Mixes 439', 'Expanded asynchronous attitude');
insert into MENU_CATEGORY (category_id, category_name, description) values (440, 'Dried Fruits 440', 'Digitized even-keeled moratorium');
insert into MENU_CATEGORY (category_id, category_name, description) values (441, 'Hydration Gear 441', 'Organized 5th generation throughput');
insert into MENU_CATEGORY (category_id, category_name, description) values (442, 'Educational Toys 442', 'Seamless multi-state website');
insert into MENU_CATEGORY (category_id, category_name, description) values (443, 'Nut-Based Snacks 443', 'Realigned well-modulated initiative');
insert into MENU_CATEGORY (category_id, category_name, description) values (444, 'Healthy Snacks 444', 'Proactive composite product');
insert into MENU_CATEGORY (category_id, category_name, description) values (445, 'Floor Care Appliances 445', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (446, 'Bean Salads 446', 'Balanced directional software');
insert into MENU_CATEGORY (category_id, category_name, description) values (447, 'Frozen Vegetables 447', 'Phased grid-enabled hub');
insert into MENU_CATEGORY (category_id, category_name, description) values (448, 'Healthy Breakfast Options 448', 'Proactive fresh-thinking adapter');
insert into MENU_CATEGORY (category_id, category_name, description) values (449, 'Laptop Accessories 449', 'Profound multi-state installation');
insert into MENU_CATEGORY (category_id, category_name, description) values (450, 'Disaster Preparedness 450', 'Open-architected coherent utilisation');
insert into MENU_CATEGORY (category_id, category_name, description) values (451, 'Soups & Broths 451', 'Managed clear-thinking alliance');
insert into MENU_CATEGORY (category_id, category_name, description) values (452, 'Phone Accessories 452', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (453, 'Sleep & Relaxation 453', 'Ameliorated reciprocal concept');
insert into MENU_CATEGORY (category_id, category_name, description) values (454, 'Cookware 454', 'Sharable optimizing secured line');
insert into MENU_CATEGORY (category_id, category_name, description) values (455, 'Outdoor Accessories 455', 'Right-sized leading edge ability');
insert into MENU_CATEGORY (category_id, category_name, description) values (456, 'Marinades and Sauces 456', 'Cross-group 24 hour matrices');
insert into MENU_CATEGORY (category_id, category_name, description) values (457, 'Marinades and Sauces 457', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (458, 'Granola/Cereal 458', 'Focused client-server functionalities');
insert into MENU_CATEGORY (category_id, category_name, description) values (459, 'Baking Accessories 459', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (460, 'Asian Condiments 460', 'Ergonomic asynchronous encryption');
insert into MENU_CATEGORY (category_id, category_name, description) values (461, 'Planters 461', 'Progressive empowering solution');
insert into MENU_CATEGORY (category_id, category_name, description) values (462, 'Cooking Appliances 462', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (463, 'Decorative Wall Art & Accessories 463', 'Horizontal uniform archive');
insert into MENU_CATEGORY (category_id, category_name, description) values (464, 'Seasoning Blends 464', 'User-centric even-keeled policy');
insert into MENU_CATEGORY (category_id, category_name, description) values (465, 'Frozen Italian Meal Kits 465', 'Visionary optimal forecast');
insert into MENU_CATEGORY (category_id, category_name, description) values (466, 'Small Appliances 466', 'Profound eco-centric superstructure');
insert into MENU_CATEGORY (category_id, category_name, description) values (467, 'Chili 467', 'Front-line zero administration orchestration');
insert into MENU_CATEGORY (category_id, category_name, description) values (468, 'Audio Equipment 468', 'Optional transitional matrix');
insert into MENU_CATEGORY (category_id, category_name, description) values (469, 'Small Appliances 469', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (470, 'Ice Cream 470', 'Self-enabling actuating software');
insert into MENU_CATEGORY (category_id, category_name, description) values (471, 'Gluten-Free Treats 471', 'Stand-alone empowering software');
insert into MENU_CATEGORY (category_id, category_name, description) values (472, 'Smoothies 472', 'Devolved cohesive algorithm');
insert into MENU_CATEGORY (category_id, category_name, description) values (473, 'Dressings 473', 'Horizontal directional middleware');
insert into MENU_CATEGORY (category_id, category_name, description) values (474, 'Granola/Cereal 474', 'Robust object-oriented Graphical User Interface');
insert into MENU_CATEGORY (category_id, category_name, description) values (475, 'Soups 475', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (476, 'Pasta & Rice Mixes 476', 'Centralized 3rd generation software');
insert into MENU_CATEGORY (category_id, category_name, description) values (477, 'Oral Care & Hygiene 477', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (478, 'Laptop Accessories 478', 'Mandatory zero administration protocol');
insert into MENU_CATEGORY (category_id, category_name, description) values (479, 'Sparkling Beverages 479', 'Programmable modular secured line');
insert into MENU_CATEGORY (category_id, category_name, description) values (480, 'Laptop Accessories 480', 'Persevering system-worthy core');
insert into MENU_CATEGORY (category_id, category_name, description) values (481, 'Canned Fruits 481', 'Persistent maximized installation');
insert into MENU_CATEGORY (category_id, category_name, description) values (482, 'Outdoor Accessories 482', 'Managed intangible migration');
insert into MENU_CATEGORY (category_id, category_name, description) values (483, 'Garden Supplies 483', 'Innovative needs-based hierarchy');
insert into MENU_CATEGORY (category_id, category_name, description) values (484, 'Mobile Accessories 484', 'Intuitive discrete adapter');
insert into MENU_CATEGORY (category_id, category_name, description) values (485, 'Frozen Meals 485', 'Streamlined impactful challenge');
insert into MENU_CATEGORY (category_id, category_name, description) values (486, 'Outdoor Recreation 486', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (487, 'Eggs 487', 'Future-proofed uniform leverage');
insert into MENU_CATEGORY (category_id, category_name, description) values (488, 'Sparkling Beverages 488', 'Horizontal real-time model');
insert into MENU_CATEGORY (category_id, category_name, description) values (489, 'Small Appliances 489', 'User-centric real-time initiative');
insert into MENU_CATEGORY (category_id, category_name, description) values (490, 'Activewear Jackets 490', 'Fundamental bandwidth-monitored approach');
insert into MENU_CATEGORY (category_id, category_name, description) values (491, 'Potatoes 491', 'Intuitive demand-driven pricing structure');
insert into MENU_CATEGORY (category_id, category_name, description) values (492, 'Pies and Tarts 492', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (493, 'Drones & Accessories 493', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (494, 'Baking Accessories 494', 'Assimilated context-sensitive definition');
insert into MENU_CATEGORY (category_id, category_name, description) values (495, 'Wallets 495', 'Multi-tiered modular system engine');
insert into MENU_CATEGORY (category_id, category_name, description) values (496, 'Vegetable Snacks 496', 'User-centric background secured line');
insert into MENU_CATEGORY (category_id, category_name, description) values (497, 'Musical Toys 497', null);
insert into MENU_CATEGORY (category_id, category_name, description) values (498, 'Eggs 498', 'Total bifurcated projection');
insert into MENU_CATEGORY (category_id, category_name, description) values (499, 'Office Supplies 499', 'Upgradable human-resource encryption');
insert into MENU_CATEGORY (category_id, category_name, description) values (500, 'Tech Accessories 500', 'Right-sized static implementation');
