insert into RECIPE (recipe_id, instructions, menu_item_id) values (1, 'Chef''s instructions: Rich and creamy dressing with garlic flavor, perfect for salads.', 1);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (2, 'Chef''s instructions: A trendy cropped sweater perfect for a casual look.', 2);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (3, 'Chef''s instructions: A savory marinade for meats, perfect for grilling.', 3);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (4, 'Chef''s instructions: A rich pesto made with sun-dried tomatoes and pine nuts.', 4);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (5, 'Chef''s instructions: Energy-efficient lights that charge during the day and illuminate at night.', 5);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (6, 'Chef''s instructions: Fluffy rice cooked with coconut milk for a tropical twist.', 6);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (7, 'Chef''s instructions: Natural energy bites packed with fruits and nuts for a perfect snack.', 7);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (8, 'Chef''s instructions: A flavorful blend of rice with tropical pineapple and coconut flavors.', 8);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (9, 'Chef''s instructions: No-bake energy bites made with peanut butter and oats.', 9);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (10, 'Chef''s instructions: A hearty vegetable curry for a quick and satisfying meal.', 10);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (11, 'Chef''s instructions: Roasted pistachios, a healthy and tasty snack.', 11);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (12, 'Chef''s instructions: Soft and fluffy whole wheat pita bread, great for wraps.', 12);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (13, 'Chef''s instructions: Comfortable and rugged boots designed for hiking.', 13);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (14, 'Chef''s instructions: Bottle with infuser for brewing loose-leaf tea on the go.', 14);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (15, 'Chef''s instructions: Creamy yogurt blended with fresh pineapple and coconut pieces.', 15);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (16, 'Chef''s instructions: Crunchy, seasoned chickpeas for a wholesome snack.', 16);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (17, 'Chef''s instructions: Quick and easy rice pilaf mix for side dishes.', 17);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (18, 'Chef''s instructions: Comfortable over-ear headphones with deep bass.', 18);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (19, 'Chef''s instructions: Durable non-stick frying pan for easy cooking and cleaning.', 19);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (20, 'Chef''s instructions: Decadent brownies made without gluten, rich and chocolatey.', 20);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (21, 'Chef''s instructions: Light and crispy baked potato chips in assorted flavors.', 21);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (22, 'Chef''s instructions: Non-stick surface for easy cooking and cleaning.', 22);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (23, 'Chef''s instructions: Frozen berries blend perfect for smoothies, just add yogurt.', 23);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (24, 'Chef''s instructions: Colorful LED strip lights for home decoration.', 24);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (25, 'Chef''s instructions: Savory sardines packed in olive oil.', 25);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (26, 'Chef''s instructions: A delightful mix of nuts, fruit, and chocolate.', 26);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (27, 'Chef''s instructions: Instant-read thermometer for accurate cooking temperatures.', 27);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (28, 'Chef''s instructions: Countertop compost bin for kitchen waste.', 28);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (29, 'Chef''s instructions: Delicious veggie burgers loaded with grilled vegetables.', 29);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (30, 'Chef''s instructions: The perfect seafood snack, ready to eat and delicious.', 30);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (31, 'Chef''s instructions: Set of stylish watch bands to customize your look.', 31);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (32, 'Chef''s instructions: A flavorful garlic butter blend, perfect for cooking or baking.', 32);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (33, 'Chef''s instructions: Compact air fryer for healthier cooking.', 33);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (34, 'Chef''s instructions: Relax and soothe tired feet with this foot spa.', 34);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (35, 'Chef''s instructions: UV light sanitizer for phones and small items.', 35);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (36, 'Chef''s instructions: Foam yoga block for enhancing poses and stability.', 36);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (37, 'Chef''s instructions: Trendy high-top canvas sneakers for a stylish streetwear look.', 37);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (38, 'Chef''s instructions: Fresh pomegranate juice, rich in antioxidants.', 38);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (39, 'Chef''s instructions: Lightweight, expandable hoses for easy handling.', 39);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (40, 'Chef''s instructions: A delicious sauce perfect for stir-frying or glazing meats.', 40);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (41, 'Chef''s instructions: Maintain freshness and dispense cereal easily.', 41);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (42, 'Chef''s instructions: Powerful grinder for making sausage and burgers at home.', 42);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (43, 'Chef''s instructions: Farm fresh eggs, essential for breakfast.', 43);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (44, 'Chef''s instructions: Sweet dried raisins, perfect for snacks or baking.', 44);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (45, 'Chef''s instructions: Crispy and juicy chicken tenders, perfect for dipping.', 45);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (46, 'Chef''s instructions: Eco-friendly meal prep containers for healthy eating.', 46);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (47, 'Chef''s instructions: Frozen chicken bites coated in a honey sriracha glaze, spicy and sweet.', 47);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (48, 'Chef''s instructions: Video baby monitor with night vision.', 48);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (49, 'Chef''s instructions: Comfortable and reusable face masks in different styles.', 49);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (50, 'Chef''s instructions: Compact hair straightener for travel.', 50);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (51, 'Chef''s instructions: Automatic water fountain for pets with filtration.', 51);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (52, 'Chef''s instructions: Tender grilled chicken marinated in lemon herbs.', 52);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (53, 'Chef''s instructions: Crunchy pretzel sticks made with honey and whole wheat.', 53);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (54, 'Chef''s instructions: Create spiraled vegetable noodles easily for healthy meals.', 54);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (55, 'Chef''s instructions: Float through the day in this beautiful floor-length skirt.', 55);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (56, 'Chef''s instructions: Protects car interior from sun damage and heat.', 56);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (57, 'Chef''s instructions: Handheld frother for creating frothed milk for coffee.', 57);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (58, 'Chef''s instructions: Crunchy cacao nibs, great for adding to smoothies or baking.', 58);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (59, 'Chef''s instructions: Delicious mini donuts dusted with cinnamon sugar.', 59);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (60, 'Chef''s instructions: Nutty-scented oil for stir-fry and marinades.', 60);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (61, 'Chef''s instructions: A refreshing salad with chickpeas, cucumber, tomatoes, and a light vinaigrette dressing.', 61);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (62, 'Chef''s instructions: Color-changing 3D night light for kids'' rooms.', 62);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (63, 'Chef''s instructions: Soft and warm corn tortillas, perfect for tacos and burritos.', 63);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (64, 'Chef''s instructions: Creamy tahini made from ground sesame seeds.', 64);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (65, 'Chef''s instructions: High-quality sketchbook for artists.', 65);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (66, 'Chef''s instructions: Unique coffee brewing method for a flavorful experience.', 66);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (67, 'Chef''s instructions: Bright and fragrant cilantro, great for garnishes.', 67);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (68, 'Chef''s instructions: Crunchy granola with oats, nuts, and honey.', 68);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (69, 'Chef''s instructions: Durable apron to keep clothes clean while cooking.', 69);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (70, 'Chef''s instructions: Freshly baked whole wheat bread, rich in fiber.', 70);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (71, 'Chef''s instructions: Light and breezy dress perfect for summer outings with a vibrant floral pattern.', 71);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (72, 'Chef''s instructions: Tangy sweet chili sauce perfect for dipping or cooking.', 72);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (73, 'Chef''s instructions: Fluffy couscous that cooks in just minutes, perfect as a side.', 73);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (74, 'Chef''s instructions: Everything you need to make melt-in-your-mouth cinnamon rolls at home.', 74);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (75, 'Chef''s instructions: Artisan bread topped with olives, feta, and herbs, perfect for sharing.', 75);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (76, 'Chef''s instructions: Crunchy, seasoned chickpeas for a wholesome snack.', 76);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (77, 'Chef''s instructions: Compact and portable backpack for day trips and travel.', 77);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (78, 'Chef''s instructions: Low-calorie rice cake for snacks.', 78);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (79, 'Chef''s instructions: A frozen meal featuring quinoa and mixed vegetables, ready to heat and eat.', 79);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (80, 'Chef''s instructions: Compact sewing kit for travel emergencies.', 80);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (81, 'Chef''s instructions: Healthy fruit snacks, made with real fruit.', 81);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (82, 'Chef''s instructions: Portable case to organize and protect jewelry on trips.', 82);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (83, 'Chef''s instructions: Convenient magnetic jars for easy spice storage.', 83);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (84, 'Chef''s instructions: Set of reusable baking cups for muffins and cupcakes.', 84);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (85, 'Chef''s instructions: Inflatable air mattress for convenient sleeping.', 85);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (86, 'Chef''s instructions: Crunchy granola with maple flavor and almond pieces for breakfast.', 86);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (87, 'Chef''s instructions: Automatically cooks eggs to your desired level.', 87);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (88, 'Chef''s instructions: Wearable device to track fitness activities and heart rate.', 88);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (89, 'Chef''s instructions: Chocolate-covered candy bars with coconut and almonds.', 89);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (90, 'Chef''s instructions: Natural honey sourced from wildflowers.', 90);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (91, 'Chef''s instructions: A warm knitted scarf to keep you cozy in winter.', 91);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (92, 'Chef''s instructions: Water-resistant jacket ideal for outdoor activities, featuring a packable design.', 92);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (93, 'Chef''s instructions: Cozy throw blanket perfect for adding warmth to your home.', 93);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (94, 'Chef''s instructions: Decorative table runner perfect for autumn gatherings.', 94);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (95, 'Chef''s instructions: Creamy chickpea dip infused with zesty garlic flavor.', 95);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (96, 'Chef''s instructions: Eco-friendly solar lights for pathways and gardens.', 96);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (97, 'Chef''s instructions: Made from biodegradable materials for eco-conscious yogis.', 97);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (98, 'Chef''s instructions: Easily opens jar lids and bottle caps with one touch.', 98);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (99, 'Chef''s instructions: Hearty stew made with lentils and mixed vegetables, vegan-friendly.', 99);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (100, 'Chef''s instructions: Manual blender for smoothies and mixing ingredients on the go.', 100);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (101, 'Chef''s instructions: Nutritious bars packed with protein for energy', 101);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (102, 'Chef''s instructions: Mint-flavored chocolate candies for a refreshing treat.', 102);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (103, 'Chef''s instructions: Collapsible dish rack for kitchen countertop use.', 103);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (104, 'Chef''s instructions: Versatile canned black beans, ready to add to any dish.', 104);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (105, 'Chef''s instructions: Rechargeable hand warmer for cold weather comfort.', 105);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (106, 'Chef''s instructions: Couscous salad with cucumbers, tomatoes, feta, and olives, ready to eat.', 106);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (107, 'Chef''s instructions: Classic V-neck sweater crafted from soft wool for warmth and style.', 107);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (108, 'Chef''s instructions: All-in-one kit for growing herbs in your kitchen.', 108);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (109, 'Chef''s instructions: Water bottle that tracks hydration levels and adds electrolytes.', 109);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (110, 'Chef''s instructions: A zesty salad with black beans, corn, and chipotle dressing.', 110);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (111, 'Chef''s instructions: Durable backpack with ample storage for outdoor adventures.', 111);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (112, 'Chef''s instructions: Assorted herbal teas, perfect for a warm and relaxing drink.', 112);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (113, 'Chef''s instructions: Extra virgin olive oil infused with fresh basil.', 113);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (114, 'Chef''s instructions: Comfortable and warm leggings perfect for colder weather.', 114);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (115, 'Chef''s instructions: Refreshing sparkling water with lemon and lime flavor', 115);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (116, 'Chef''s instructions: 500-piece jigsaw puzzle featuring beautiful scenery.', 116);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (117, 'Chef''s instructions: Stylish desk set to keep your workspace tidy and organized.', 117);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (118, 'Chef''s instructions: Portable solar shower for camping and outdoor use.', 118);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (119, 'Chef''s instructions: Convenient stroller for pets to enjoy outdoor walks.', 119);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (120, 'Chef''s instructions: Cold-pressed coconut oil, perfect for cooking, baking, or skin care.', 120);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (121, 'Chef''s instructions: Crunchy granola made with organic oats', 121);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (122, 'Chef''s instructions: Delicious vegetable dumplings, perfect for steaming or frying.', 122);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (123, 'Chef''s instructions: Complete tattoo kit for beginners and professionals.', 123);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (124, 'Chef''s instructions: Prepped vegetables and sauces for a quick Asian stir-fry meal.', 124);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (125, 'Chef''s instructions: Floral and refreshing herbal tea, great hot or iced.', 125);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (126, 'Chef''s instructions: Compact towels that expand when wet, ideal for travel.', 126);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (127, 'Chef''s instructions: Add a smoky flavor to your dishes.', 127);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (128, 'Chef''s instructions: Rich dark chocolate bars, perfect for a sweet treat.', 128);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (129, 'Chef''s instructions: Eco-friendly utensil set made from natural wood.', 129);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (130, 'Chef''s instructions: Durable and non-stick ceramic cookware for healthy cooking.', 130);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (131, 'Chef''s instructions: Creamy vanilla fudge, a sweet treat for all occasions.', 131);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (132, 'Chef''s instructions: Sweet and juicy strawberries, perfect for desserts.', 132);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (133, 'Chef''s instructions: Comprehensive first aid kit for home or travel emergencies.', 133);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (134, 'Chef''s instructions: Classic A-line skirt that flatters every figure, perfect for work or play.', 134);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (135, 'Chef''s instructions: Chewy bars made with peanut butter and chocolate chips.', 135);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (136, 'Chef''s instructions: Flavorful lentil soup, perfect for a quick meal.', 136);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (137, 'Chef''s instructions: Comfortable pillow with built-in massage features.', 137);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (138, 'Chef''s instructions: Adds extra comfort to your mattress for a better night''s sleep.', 138);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (139, 'Chef''s instructions: Efficient juicer for fresh fruit and vegetable juices.', 139);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (140, 'Chef''s instructions: Breathable polo shirt designed for both style and comfort on the greens.', 140);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (141, 'Chef''s instructions: Soft pita bread, perfect for sandwiches or dips.', 141);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (142, 'Chef''s instructions: Seat belt attachment to keep dogs safe during car rides.', 142);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (143, 'Chef''s instructions: Whole grain oats that are perfect for breakfast or baking.', 143);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (144, 'Chef''s instructions: Personal massager for muscle recovery.', 144);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (145, 'Chef''s instructions: Convenient carrier for transporting yoga mat.', 145);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (146, 'Chef''s instructions: Fast and compact external solid state drive, 1TB.', 146);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (147, 'Chef''s instructions: Rechargeable training collar for effective behavior training.', 147);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (148, 'Chef''s instructions: Rich and smooth cold brew coffee concentrate, just add water or milk.', 148);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (149, 'Chef''s instructions: A hearty soup made with lentils, coconut milk, and a blend of spices for a tropical flavor.', 149);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (150, 'Chef''s instructions: Colorful veggie chips made from beets, carrots, and sweet potatoes.', 150);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (151, 'Chef''s instructions: Multiple USB ports for charging devices simultaneously.', 151);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (152, 'Chef''s instructions: Fresh basil pesto, perfect for pasta or as a sandwich spread.', 152);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (153, 'Chef''s instructions: Travel-friendly dog bowl that is collapsible for easy storage.', 153);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (154, 'Chef''s instructions: Comfortable pet carrier for travel and vet visits.', 154);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (155, 'Chef''s instructions: Wild-caught tuna in olive oil, perfect for salads.', 155);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (156, 'Chef''s instructions: Portable chess set with magnetic pieces for travel.', 156);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (157, 'Chef''s instructions: Creamy mashed sweet potatoes, ready to heat and serve.', 157);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (158, 'Chef''s instructions: Light and crispy baked potato chips in assorted flavors.', 158);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (159, 'Chef''s instructions: Coffee blend infused with pumpkin spice, perfect for fall.', 159);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (160, 'Chef''s instructions: Float through the day in this beautiful floor-length skirt.', 160);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (161, 'Chef''s instructions: Breathable polo shirt designed for both style and comfort on the greens.', 161);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (162, 'Chef''s instructions: Supportive yoga wheel for deep stretching and balance.', 162);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (163, 'Chef''s instructions: A spicy glaze made with sriracha and honey, perfect for meats.', 163);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (164, 'Chef''s instructions: Creamy peach-flavored yogurt with real fruit.', 164);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (165, 'Chef''s instructions: Salted sunflower seeds perfect for snacking.', 165);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (166, 'Chef''s instructions: A natural sweetener made from coconut sap, a healthier alternative to sugar.', 166);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (167, 'Chef''s instructions: Traditional Korean fermented vegetables, packed with flavor.', 167);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (168, 'Chef''s instructions: Cozy throw blanket perfect for adding warmth to your home.', 168);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (169, 'Chef''s instructions: Waterproof picnic blanket for outdoor fun.', 169);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (170, 'Chef''s instructions: Eco-friendly charger that uses solar energy for powering devices.', 170);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (171, 'Chef''s instructions: Colorful and child-friendly gardening tools for little hands.', 171);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (172, 'Chef''s instructions: Cozy beanie hat to keep your head warm in the cold.', 172);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (173, 'Chef''s instructions: Rich and creamy chocolate fudge ice cream for dessert.', 173);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (174, 'Chef''s instructions: Breathable tank top perfect for workouts or casual wear.', 174);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (175, 'Chef''s instructions: Portable desk that can be adjusted for sitting or standing.', 175);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (176, 'Chef''s instructions: Creamy Greek yogurt packed with protein and probiotics.', 176);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (177, 'Chef''s instructions: Fresh seedless red grapes, perfect for snacking.', 177);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (178, 'Chef''s instructions: Silicone oven mitts designed for safe cooking and baking.', 178);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (179, 'Chef''s instructions: Qi-certified wireless charger for fast charging.', 179);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (180, 'Chef''s instructions: High-quality whey protein powder for muscle recovery.', 180);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (181, 'Chef''s instructions: Light and fluffy popcorn coated in sweet honey butter.', 181);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (182, 'Chef''s instructions: Durable canvas tote bag, perfect for everyday use.', 182);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (183, 'Chef''s instructions: Versatile multi-tool with 15 different functions.', 183);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (184, 'Chef''s instructions: Portable induction cooktop for quick heating.', 184);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (185, 'Chef''s instructions: Soft glow night light for children''s rooms or bedside.', 185);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (186, 'Chef''s instructions: Adjustable tripod with remote shutter for smartphones.', 186);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (187, 'Chef''s instructions: Creamy dessert made with rice and cinnamon.', 187);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (188, 'Chef''s instructions: Countertop compost bin for kitchen waste.', 188);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (189, 'Chef''s instructions: Crispy mini pretzels, a great snack any time of day.', 189);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (190, 'Chef''s instructions: Durable backpack for hiking or travel.', 190);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (191, 'Chef''s instructions: Creamy vegan mac and cheese made with cashew cheese.', 191);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (192, 'Chef''s instructions: Creamy and delicious soup made with real butternut squash, ready to heat.', 192);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (193, 'Chef''s instructions: Smart tracker to locate keys or other items via app.', 193);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (194, 'Chef''s instructions: Compostable plates suitable for various occasions.', 194);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (195, 'Chef''s instructions: Eco-friendly bags for storing food without plastic waste.', 195);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (196, 'Chef''s instructions: Eco-friendly generator for outdoor adventures.', 196);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (197, 'Chef''s instructions: Monitor and interact with your pet remotely with this camera.', 197);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (198, 'Chef''s instructions: All-in-one kit for making pasta salad easily.', 198);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (199, 'Chef''s instructions: Custom keychain with engraved text.', 199);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (200, 'Chef''s instructions: Fluffy rice cooked with coconut milk for a tropical twist.', 200);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (201, 'Chef''s instructions: Healthy pizza crust made from cauliflower', 201);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (202, 'Chef''s instructions: Fast and accurate thermometer for grilling and cooking.', 202);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (203, 'Chef''s instructions: Set of unique wooden coasters for drinks and decor.', 203);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (204, 'Chef''s instructions: Delicious dark chocolate with creamy nut butter inside.', 204);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (205, 'Chef''s instructions: Classic ranch dressing for salads and dipping.', 205);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (206, 'Chef''s instructions: High-quality headphones that block out external noise for immersive listening.', 206);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (207, 'Chef''s instructions: Creamy Greek yogurt packed with protein and probiotics.', 207);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (208, 'Chef''s instructions: Space-saving crates for easy organization at home or while traveling.', 208);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (209, 'Chef''s instructions: A colorful printed maxi skirt for a bohemian look.', 209);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (210, 'Chef''s instructions: Delicious ravioli filled with creamy ricotta and fresh spinach.', 210);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (211, 'Chef''s instructions: Natural elderberry syrup to boost immunity.', 211);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (212, 'Chef''s instructions: 64GB SD memory card for cameras and devices.', 212);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (213, 'Chef''s instructions: Delicious vegetable dumplings, perfect for steaming or frying.', 213);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (214, 'Chef''s instructions: Nutritious protein bar with cherry and almond flavor, great for on-the-go.', 214);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (215, 'Chef''s instructions: Delicious and fully cooked sliced ham, ready to eat.', 215);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (216, 'Chef''s instructions: Fashionable wide-leg trousers for a chic silhouette.', 216);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (217, 'Chef''s instructions: Smoothie mix combining peanut butter and banana, great for a quick breakfast.', 217);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (218, 'Chef''s instructions: Large, durable tote bag for shopping and outdoor activities.', 218);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (219, 'Chef''s instructions: A delicious sauce perfect for stir-frying or glazing meats.', 219);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (220, 'Chef''s instructions: A fresh, flavorful basil pesto for pasta and more', 220);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (221, 'Chef''s instructions: Space-saving adjustable dumbbells for strength training.', 221);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (222, 'Chef''s instructions: Space-efficient shoe rack to keep entryways organized.', 222);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (223, 'Chef''s instructions: Ceramic pizza stone for homemade pizzas.', 223);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (224, 'Chef''s instructions: Shrimp marinated in a honey garlic sauce, ready to cook.', 224);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (225, 'Chef''s instructions: Fun robot that engages kids with games and activities.', 225);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (226, 'Chef''s instructions: Handy belt for carrying garden tools while working.', 226);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (227, 'Chef''s instructions: Crunchy granola with cranberries and pecans.', 227);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (228, 'Chef''s instructions: A mix of nuts, pretzels, and crackers, seasoned just right for snacking.', 228);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (229, 'Chef''s instructions: Everything you need to make your own candles.', 229);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (230, 'Chef''s instructions: Designed for comfort and performance during workouts.', 230);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (231, 'Chef''s instructions: Everything you need to create a hearty beef stroganoff.', 231);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (232, 'Chef''s instructions: Reusable silicone mats for non-stick baking.', 232);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (233, 'Chef''s instructions: A spicy, flavorful cheese stick great for snacks or lunchboxes.', 233);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (234, 'Chef''s instructions: Rechargeable training collar for effective behavior training.', 234);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (235, 'Chef''s instructions: Fun book filled with puzzles and games for kids.', 235);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (236, 'Chef''s instructions: Fresh greens and veggies for a quick Asian-inspired salad.', 236);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (237, 'Chef''s instructions: Artisan bread topped with olives, feta, and herbs, perfect for sharing.', 237);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (238, 'Chef''s instructions: Wi-Fi camera with motion detection for home security.', 238);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (239, 'Chef''s instructions: A hearty salad with lentils, veggies, and curry dressing.', 239);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (240, 'Chef''s instructions: Insulated mug to keep drinks hot on the go.', 240);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (241, 'Chef''s instructions: Frozen chicken bites coated in a honey sriracha glaze, spicy and sweet.', 241);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (242, 'Chef''s instructions: Stylish smartwatch with fitness tracking features.', 242);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (243, 'Chef''s instructions: Rechargeable electric razor for a smooth shave.', 243);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (244, 'Chef''s instructions: Delicious cookies with cranberries and almonds in every bite.', 244);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (245, 'Chef''s instructions: Fresh zucchini, versatile for grilling or sautéing.', 245);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (246, 'Chef''s instructions: Cook rice and steam vegetables simultaneously for healthy meals.', 246);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (247, 'Chef''s instructions: Versatile electric skillet for stir-frying and searing.', 247);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (248, 'Chef''s instructions: A warming blend of ginger and turmeric for lattes.', 248);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (249, 'Chef''s instructions: Elegant glass teapot for brewing loose tea.', 249);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (250, 'Chef''s instructions: Complete kit for growing herbs indoors.', 250);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (251, 'Chef''s instructions: Eco-friendly bags for picking up after your pet.', 251);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (252, 'Chef''s instructions: Challenging puzzle game set for family entertainment.', 252);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (253, 'Chef''s instructions: Precision cooker for perfect sous vide cooking.', 253);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (254, 'Chef''s instructions: Water bottle designed to infuse flavors from fruits.', 254);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (255, 'Chef''s instructions: Organize travel documents, passport, and cards.', 255);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (256, 'Chef''s instructions: A ready-to-eat salad made with chickpeas and veggies.', 256);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (257, 'Chef''s instructions: Creamy and crumbly cheese for salads and dishes.', 257);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (258, 'Chef''s instructions: Essential tools for bike maintenance and repair.', 258);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (259, 'Chef''s instructions: Craft your own lip balms with this complete kit.', 259);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (260, 'Chef''s instructions: Creamy ice cream with refreshing mint flavor and chocolate chips.', 260);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (261, 'Chef''s instructions: Soft bagels flavored with cinnamon and raisins.', 261);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (262, 'Chef''s instructions: Silicone oven mitts for safe handling of hot cookware.', 262);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (263, 'Chef''s instructions: Ziti pasta baked with marinara and parmesan cheese', 263);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (264, 'Chef''s instructions: Refreshing tea with honey and lemon flavor, perfect for a warm drink.', 264);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (265, 'Chef''s instructions: Crunchy and sweet banana chips, a great on-the-go snack.', 265);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (266, 'Chef''s instructions: Creamy hummus with a kick of spice, great for dipping.', 266);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (267, 'Chef''s instructions: Large, durable tote bag for shopping and outdoor activities.', 267);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (268, 'Chef''s instructions: Energy-efficient infrared heater for home use.', 268);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (269, 'Chef''s instructions: Bottle that tracks your water intake and reminds you to drink.', 269);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (270, 'Chef''s instructions: Aromatic long-grain basmati rice, perfect for curries.', 270);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (271, 'Chef''s instructions: Durable scoop for perfectly shaped ice cream servings.', 271);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (272, 'Chef''s instructions: Non-slip yoga mat for optimal grip and comfort.', 272);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (273, 'Chef''s instructions: A chic leather crossbody bag for everyday use.', 273);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (274, 'Chef''s instructions: A delightful mix of dried fruits for trail mix or snacks.', 274);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (275, 'Chef''s instructions: Everything you need to make melt-in-your-mouth cinnamon rolls at home.', 275);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (276, 'Chef''s instructions: Electric foot massager with heat settings.', 276);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (277, 'Chef''s instructions: Chickpeas served with olives, feta, and hummus, a healthy meal.', 277);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (278, 'Chef''s instructions: Crispy cauliflower bites tossed in spicy buffalo sauce.', 278);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (279, 'Chef''s instructions: Personalized calendar with your favorite photos.', 279);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (280, 'Chef''s instructions: Reusable suction cup hooks for hanging items.', 280);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (281, 'Chef''s instructions: Crisp and delicious organic apples.', 281);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (282, 'Chef''s instructions: Juicy raisins coated in rich dark chocolate.', 282);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (283, 'Chef''s instructions: Frozen zucchini slices coated in parmesan cheese, perfect for baking or frying.', 283);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (284, 'Chef''s instructions: DIY projector that magnifies your smartphone screen for movie nights.', 284);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (285, 'Chef''s instructions: Fast and convenient air pump for inflating toys and furniture.', 285);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (286, 'Chef''s instructions: Compact jump starter for emergency vehicle starts.', 286);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (287, 'Chef''s instructions: Weighted jump rope that counts jumps and calories burned.', 287);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (288, 'Chef''s instructions: Artisan-made sourdough bread with a tangy flavor.', 288);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (289, 'Chef''s instructions: Crunchy and sweet banana chips, a great on-the-go snack.', 289);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (290, 'Chef''s instructions: Creamy yogurt made with coconut milk', 290);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (291, 'Chef''s instructions: Easy-to-install lights to brighten kitchen cabinets and workspaces.', 291);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (292, 'Chef''s instructions: Spicy buffalo sauce ideal for wings or dipping.', 292);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (293, 'Chef''s instructions: Stylish baskets for organizing various items in your home.', 293);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (294, 'Chef''s instructions: Lightweight and durable hammock for relaxing in nature.', 294);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (295, 'Chef''s instructions: Stylish markers for labeling your indoor garden plants.', 295);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (296, 'Chef''s instructions: Crunchy granola with chocolate and hazelnuts for breakfast.', 296);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (297, 'Chef''s instructions: Convenient belt with pockets for easy access to tools while gardening.', 297);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (298, 'Chef''s instructions: Just add water for a hearty cheese and broccoli soup in minutes.', 298);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (299, 'Chef''s instructions: Fresh and zesty salsa, perfect for nachos.', 299);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (300, 'Chef''s instructions: Sweet popcorn coated in a mixture of cinnamon and sugar.', 300);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (301, 'Chef''s instructions: String lights for decorating holiday trees.', 301);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (302, 'Chef''s instructions: DIY kit to make your own elderberry syrup.', 302);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (303, 'Chef''s instructions: Durable and insulated water bottle to keep beverages cold.', 303);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (304, 'Chef''s instructions: Fun kit for aspiring explorers with binoculars and a compass.', 304);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (305, 'Chef''s instructions: Stylish hooks to easily hang shower curtains.', 305);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (306, 'Chef''s instructions: Set of ceramic knives for precision slicing.', 306);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (307, 'Chef''s instructions: Miso paste for making traditional Japanese miso soup.', 307);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (308, 'Chef''s instructions: Set of resistance bands for versatile strength training workouts.', 308);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (309, 'Chef''s instructions: Electric indoor grill for quick meals.', 309);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (310, 'Chef''s instructions: Delicious veggie burgers loaded with grilled vegetables.', 310);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (311, 'Chef''s instructions: Creamy yogurt blended with fresh pineapple and coconut pieces.', 311);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (312, 'Chef''s instructions: Lightly salted frozen edamame, a protein-packed snack.', 312);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (313, 'Chef''s instructions: Savory, protein-rich beef jerky for on-the-go snacking.', 313);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (314, 'Chef''s instructions: All-in-one kit for brewing beer at home.', 314);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (315, 'Chef''s instructions: Ergonomically designed pillow with breathable bamboo cover.', 315);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (316, 'Chef''s instructions: Compact action camera for capturing adventures.', 316);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (317, 'Chef''s instructions: Space-saving bike for indoor workouts.', 317);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (318, 'Chef''s instructions: Wheeled cooler for transporting drinks and snacks.', 318);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (319, 'Chef''s instructions: A frozen pizza topped with fresh mozzarella, tomatoes, and basil.', 319);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (320, 'Chef''s instructions: Versatile canvas sneakers suitable for everyday wear with a comfortable fit.', 320);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (321, 'Chef''s instructions: Crispy sweet potato fries, perfectly seasoned and baked to perfection.', 321);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (322, 'Chef''s instructions: Portable solar charger for outdoor adventures.', 322);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (323, 'Chef''s instructions: Fluffy rice cooked with coconut milk for a tropical twist.', 323);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (324, 'Chef''s instructions: Portable rechargeable warmer for cold days.', 324);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (325, 'Chef''s instructions: Pre-cooked vegetable fried rice, just heat and serve.', 325);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (326, 'Chef''s instructions: A staple v-neck t-shirt that pairs well with anything.', 326);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (327, 'Chef''s instructions: Crispy sweet potato fries, perfectly seasoned and baked to perfection.', 327);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (328, 'Chef''s instructions: Non-contact thermometer for quick and easy temperature readings.', 328);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (329, 'Chef''s instructions: Plant-based mayonnaise for a creamy taste.', 329);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (330, 'Chef''s instructions: Lightweight tennis racket for beginners and advanced players.', 330);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (331, 'Chef''s instructions: Compact projector for movies and presentations on the go.', 331);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (332, 'Chef''s instructions: Sweet pineapple chunks in syrup.', 332);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (333, 'Chef''s instructions: Tangy sweet chili sauce perfect for dipping or cooking.', 333);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (334, 'Chef''s instructions: Pasta tossed with fresh basil pesto, simple and delicious.', 334);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (335, 'Chef''s instructions: Compact laundry bag for travel use.', 335);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (336, 'Chef''s instructions: Precision cooker for perfect sous vide cooking.', 336);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (337, 'Chef''s instructions: Fairy lights perfect for decorating patios and backyards.', 337);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (338, 'Chef''s instructions: Crunchy granola with almonds and a hint of vanilla, perfect for breakfast.', 338);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (339, 'Chef''s instructions: Stylish ripped boyfriend jeans for a relaxed, effortlessly cool vibe.', 339);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (340, 'Chef''s instructions: Polarized sunglasses with UV protection.', 340);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (341, 'Chef''s instructions: Juicy peach slices in syrup, perfect for desserts.', 341);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (342, 'Chef''s instructions: Ready-to-eat salad with quinoa and kale, drizzled with vinaigrette.', 342);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (343, 'Chef''s instructions: Just add water for a quick pasta sauce.', 343);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (344, 'Chef''s instructions: Adjustable LED desk light with brightness settings.', 344);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (345, 'Chef''s instructions: Crunchy granola with raisins and cinnamon for a delightful breakfast.', 345);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (346, 'Chef''s instructions: Handy keychain that emits a loud alarm for personal safety.', 346);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (347, 'Chef''s instructions: Canned beans with chili sauce, perfect for chili dishes.', 347);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (348, 'Chef''s instructions: Rich and buttery mashed potatoes with roasted garlic.', 348);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (349, 'Chef''s instructions: Large electric griddle for family meals.', 349);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (350, 'Chef''s instructions: Crispy and delicious biscotti flavored with cranberry and almond.', 350);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (351, 'Chef''s instructions: Lightweight cover-up perfect for the beach, with a breezy design.', 351);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (352, 'Chef''s instructions: Continuous stream of fresh water for pets, promoting hydration.', 352);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (353, 'Chef''s instructions: Crunchy corn chips flavored with chili and lime for a zesty kick.', 353);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (354, 'Chef''s instructions: Passive noise reduction headphones for focus.', 354);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (355, 'Chef''s instructions: Durable cover to protect your grill from the elements.', 355);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (356, 'Chef''s instructions: A feminine wrap top with a beautiful floral print.', 356);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (357, 'Chef''s instructions: A stylish midi dress with stylish pleats, suitable for any occasion.', 357);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (358, 'Chef''s instructions: A complete meal kit containing breaded chicken breast, marinara sauce, and pasta, perfect for a quick dinner.', 358);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (359, 'Chef''s instructions: Frozen smoothie blend with berries for a quick and healthy breakfast.', 359);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (360, 'Chef''s instructions: Portable car vacuum cleaner with strong suction.', 360);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (361, 'Chef''s instructions: Adjustable laptop stand for better ergonomics.', 361);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (362, 'Chef''s instructions: Portable and lightweight umbrella for protection from rain.', 362);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (363, 'Chef''s instructions: Roasted almonds coated in a sweet maple and cinnamon mixture.', 363);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (364, 'Chef''s instructions: Laundry bags perfect for delicates and organizing clothes.', 364);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (365, 'Chef''s instructions: Personalized calendar with your favorite photos.', 365);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (366, 'Chef''s instructions: Sweet and spicy salsa made with fresh peaches.', 366);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (367, 'Chef''s instructions: Lightweight and durable hammock for relaxing in nature.', 367);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (368, 'Chef''s instructions: Rotating spice rack with 20 spice jars.', 368);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (369, 'Chef''s instructions: Handheld vacuum cleaner for quick and easy cleaning.', 369);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (370, 'Chef''s instructions: Ergonomic footrest for easier pedicure treatment.', 370);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (371, 'Chef''s instructions: Organize your board games with this storage bin.', 371);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (372, 'Chef''s instructions: Frozen pizza loaded with vegetables and cheese.', 372);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (373, 'Chef''s instructions: Add a smoky flavor to your dishes.', 373);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (374, 'Chef''s instructions: Fun light that creates a disco atmosphere for parties.', 374);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (375, 'Chef''s instructions: Variety pack of sticky notes in different colors and sizes.', 375);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (376, 'Chef''s instructions: Rich and creamy chocolate fudge ice cream for dessert.', 376);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (377, 'Chef''s instructions: A zesty marinade made with lemon juice and garlic, ideal for chicken or fish.', 377);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (378, 'Chef''s instructions: Soft and fluffy whole wheat pita bread, great for wraps.', 378);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (379, 'Chef''s instructions: Secure phone mount that wirelessly charges your device while driving.', 379);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (380, 'Chef''s instructions: Handheld vacuum cleaner for quick and easy cleaning.', 380);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (381, 'Chef''s instructions: Tripod with wireless remote for effortless photo-taking.', 381);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (382, 'Chef''s instructions: Stay dry with these stylish waterproof rain boots.', 382);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (383, 'Chef''s instructions: Savory hash made with sweet potatoes and kale, a perfect side dish.', 383);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (384, 'Chef''s instructions: A creamy pumpkin soup with a blend of warm spices, ready to heat and serve.', 384);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (385, 'Chef''s instructions: Bottle that tracks your water intake and reminds you to drink.', 385);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (386, 'Chef''s instructions: Delicious canned pineapple rings for desserts or salads.', 386);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (387, 'Chef''s instructions: A crunchy blend of nuts and pretzels with a spicy kick.', 387);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (388, 'Chef''s instructions: Compact Bluetooth speaker with rich sound quality.', 388);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (389, 'Chef''s instructions: Portable water bottle for pets when traveling.', 389);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (390, 'Chef''s instructions: Add a pop of color with this stylish patterned knit scarf.', 390);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (391, 'Chef''s instructions: A spicy glaze made with sriracha and honey, perfect for meats.', 391);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (392, 'Chef''s instructions: Compact waffle maker for perfect small waffles.', 392);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (393, 'Chef''s instructions: Polarized sunglasses with UV protection.', 393);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (394, 'Chef''s instructions: Creamy hummus with a kick of spice, great for dipping.', 394);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (395, 'Chef''s instructions: Fashionable wide-leg trousers for a chic silhouette.', 395);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (396, 'Chef''s instructions: Healthy energy bites made with oats and natural sweeteners.', 396);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (397, 'Chef''s instructions: Space-saving rack to store and organize spices conveniently.', 397);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (398, 'Chef''s instructions: Compact USB fan for personal cooling.', 398);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (399, 'Chef''s instructions: Multi-level scratching post to keep your cat entertained.', 399);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (400, 'Chef''s instructions: Mild cheese great for sandwiches.', 400);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (401, 'Chef''s instructions: Savory hash made with sweet potatoes and kale, a perfect side dish.', 401);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (402, 'Chef''s instructions: Programmable pet feeder for scheduled meals.', 402);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (403, 'Chef''s instructions: Comfortable camping mattress that inflates automatically.', 403);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (404, 'Chef''s instructions: A ready-to-eat soup with coconut milk, spices, and vegetables.', 404);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (405, 'Chef''s instructions: Healthy salad made with chickpeas, vegetables, and a lemon dressing.', 405);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (406, 'Chef''s instructions: Smooth and creamy smoothie made with peanut butter and banana.', 406);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (407, 'Chef''s instructions: A smoky barbecue sauce, ideal for grilling and dipping.', 407);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (408, 'Chef''s instructions: Assorted indoor plants for home decor.', 408);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (409, 'Chef''s instructions: Sweet and tender peach slices preserved in syrup, great for desserts.', 409);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (410, 'Chef''s instructions: Windshield sunshade for car interior protection.', 410);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (411, 'Chef''s instructions: Easy-to-read digital kitchen timer with alarms.', 411);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (412, 'Chef''s instructions: Effective laundry detergent for a deep clean.', 412);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (413, 'Chef''s instructions: Soft and comfortable robe, perfect for lounging at home.', 413);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (414, 'Chef''s instructions: Seasoned and roasted to perfection, ready to eat.', 414);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (415, 'Chef''s instructions: Timeless belted trench coat for a polished look during fall.', 415);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (416, 'Chef''s instructions: Fresh sushi rolls filled with a variety of vegetables.', 416);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (417, 'Chef''s instructions: Set of resistance bands for versatile strength training workouts.', 417);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (418, 'Chef''s instructions: Classic A-line skirt that flatters every figure, perfect for work or play.', 418);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (419, 'Chef''s instructions: Fun decorations for Halloween to set a spooky atmosphere.', 419);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (420, 'Chef''s instructions: Set of elegant wine glasses for special occasions.', 420);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (421, 'Chef''s instructions: Unsweetened apple sauce, great for snacks or baking.', 421);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (422, 'Chef''s instructions: Delicious ravioli filled with creamy ricotta and fresh spinach.', 422);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (423, 'Chef''s instructions: Rich and flavorful pasta sauce made with ripe tomatoes and basil.', 423);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (424, 'Chef''s instructions: Classic chino shorts in a versatile color for summer adventures.', 424);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (425, 'Chef''s instructions: Fun light that creates a disco atmosphere for parties.', 425);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (426, 'Chef''s instructions: Delicate green tea leaves for a refreshing beverage.', 426);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (427, 'Chef''s instructions: Ready-to-eat salad with kale, lemon, and cheese.', 427);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (428, 'Chef''s instructions: High-quality whey protein powder for muscle recovery.', 428);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (429, 'Chef''s instructions: A hearty soup made with lentils, a variety of vegetables, and spices, ideal for a nutritious meal.', 429);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (430, 'Chef''s instructions: Delicious apple sauce with a hint of cinnamon', 430);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (431, 'Chef''s instructions: Compact hand mixer for easy baking.', 431);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (432, 'Chef''s instructions: A fitted ribbed knit dress that hugs your curves perfectly.', 432);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (433, 'Chef''s instructions: Portable desk that can be adjusted for sitting or standing.', 433);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (434, 'Chef''s instructions: Insulated water bottle for keeping drinks cold.', 434);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (435, 'Chef''s instructions: A spicy marinade perfect for chicken and fish.', 435);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (436, 'Chef''s instructions: Complete set for garden care with a handy carrying bag.', 436);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (437, 'Chef''s instructions: A warm knitted scarf to keep you cozy in winter.', 437);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (438, 'Chef''s instructions: A smoky barbecue sauce, ideal for grilling and dipping.', 438);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (439, 'Chef''s instructions: Light and crispy baked potato chips in assorted flavors.', 439);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (440, 'Chef''s instructions: Wi-Fi enabled thermostat that learns your habits.', 440);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (441, 'Chef''s instructions: Reversible bamboo chopping board for food prep.', 441);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (442, 'Chef''s instructions: Abstract canvas print to enhance home decor.', 442);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (443, 'Chef''s instructions: Organized tackle box for fishing gear.', 443);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (444, 'Chef''s instructions: Hearty casserole with beef and enchilada sauce.', 444);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (445, 'Chef''s instructions: A mix of fresh raspberries, blueberries, and blackberries.', 445);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (446, 'Chef''s instructions: Digital scale to avoid overweight baggage fees.', 446);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (447, 'Chef''s instructions: Ergonomic memory foam pillow for better sleep.', 447);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (448, 'Chef''s instructions: Tangy sweet chili sauce perfect for dipping or cooking.', 448);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (449, 'Chef''s instructions: Blend of cheddar and mozzarella cheese, great for recipes.', 449);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (450, 'Chef''s instructions: Smoky and sweet BBQ sauce for grilling and dipping.', 450);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (451, 'Chef''s instructions: Adjustable laptop stand for better ergonomics.', 451);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (452, 'Chef''s instructions: Set of stylish watch bands to customize your look.', 452);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (453, 'Chef''s instructions: Non-toxic traps for catching household pests safely.', 453);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (454, 'Chef''s instructions: Space-saving collapsible bottle for outdoor activities.', 454);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (455, 'Chef''s instructions: Juicy and tender beef sirloin steak, grass-fed.', 455);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (456, 'Chef''s instructions: Delicate ravioli filled with roasted butternut squash and spices, perfect with a sage butter sauce.', 456);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (457, 'Chef''s instructions: Energy-efficient LED bulbs that can be controlled via smartphone.', 457);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (458, 'Chef''s instructions: Leak-proof bottles for travel-sized toiletries.', 458);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (459, 'Chef''s instructions: A rich coconut curry sauce perfect for simmering vegetables or meats.', 459);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (460, 'Chef''s instructions: Delicious waffles infused with pumpkin and spices.', 460);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (461, 'Chef''s instructions: Beautifully crafted jewelry box with compartments for storage.', 461);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (462, 'Chef''s instructions: Nutty flavor perfect for pesto and salads.', 462);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (463, 'Chef''s instructions: Stylish and functional backpack for school or trips.', 463);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (464, 'Chef''s instructions: Sweet and fruity peach preserves, perfect for spreading on toast.', 464);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (465, 'Chef''s instructions: Light and crunchy rice cakes with a variety of flavors.', 465);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (466, 'Chef''s instructions: True wireless earbuds with touch control.', 466);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (467, 'Chef''s instructions: Single-serve coffee maker with a built-in grinder.', 467);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (468, 'Chef''s instructions: Convenient and low-carb alternative to traditional rice.', 468);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (469, 'Chef''s instructions: Creamy mashed sweet potatoes, ready to heat and serve.', 469);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (470, 'Chef''s instructions: Adjustable shower head for a luxurious shower experience.', 470);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (471, 'Chef''s instructions: Spicy sauce perfect for chicken wings and dipping.', 471);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (472, 'Chef''s instructions: High-quality leather wallet with multiple compartments.', 472);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (473, 'Chef''s instructions: Essential ingredient for baking fluffy cakes and pastries.', 473);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (474, 'Chef''s instructions: High-frequency whistle for training your dog effectively.', 474);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (475, 'Chef''s instructions: Set with various resistance bands for workouts.', 475);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (476, 'Chef''s instructions: High-quality whole wheat flour for baking and cooking.', 476);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (477, 'Chef''s instructions: A flavorful blend of rice with tropical pineapple and coconut flavors.', 477);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (478, 'Chef''s instructions: Regulate water temperature for safe and comfortable showers.', 478);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (479, 'Chef''s instructions: Durable backpack with ample storage for outdoor adventures.', 479);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (480, 'Chef''s instructions: Comfortable eye mask that includes noise-canceling ear plugs.', 480);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (481, 'Chef''s instructions: Creamy and rich vanilla ice cream, a classic dessert.', 481);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (482, 'Chef''s instructions: A ready-to-eat soup with coconut milk, spices, and vegetables.', 482);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (483, 'Chef''s instructions: A rich pesto made with sun-dried tomatoes and pine nuts.', 483);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (484, 'Chef''s instructions: Delicious veggie burger patties for grilling or frying.', 484);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (485, 'Chef''s instructions: Protein-rich quinoa, a great alternative to rice.', 485);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (486, 'Chef''s instructions: Crispy and sweet dried apple slices', 486);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (487, 'Chef''s instructions: Fresh greens and veggies for a quick Asian-inspired salad.', 487);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (488, 'Chef''s instructions: Sweetened sticky rice served with fresh mango and coconut sauce.', 488);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (489, 'Chef''s instructions: Creamy mayonnaise, perfect for salads and sandwiches.', 489);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (490, 'Chef''s instructions: Solar-powered charger for smartphones and tablets.', 490);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (491, 'Chef''s instructions: Classic ketchup made from organic tomatoes, no added sugar.', 491);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (492, 'Chef''s instructions: Spicy cauliflower bites for a vegetarian snack.', 492);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (493, 'Chef''s instructions: Retro-style graphic tee with a soft wash for a vintage feel.', 493);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (494, 'Chef''s instructions: Fresh salad with pears, gorgonzola cheese, and nuts, perfect for lunch.', 494);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (495, 'Chef''s instructions: Supportive pillow designed for a good night''s sleep.', 495);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (496, 'Chef''s instructions: Portable desk that can be adjusted for sitting or standing.', 496);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (497, 'Chef''s instructions: Convenient dispenser for dog waste bags on walks.', 497);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (498, 'Chef''s instructions: Supportive pillow designed for a good night''s sleep.', 498);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (499, 'Chef''s instructions: Crispy sweet potato fries, a delicious side dish.', 499);
insert into RECIPE (recipe_id, instructions, menu_item_id) values (500, 'Chef''s instructions: Retro-style graphic tee with a soft wash for a vintage feel.', 500);
